- src/authentication/Credentials.ts
- src/authentication/CredentialsExtractor.ts
- src/authorization/Authorizer.ts
- src/ldp/http/Patch.ts
- src/ldp/http/RequestParser.ts
- src/ldp/operations/OperationHandler.ts
- src/ldp/permissions/PermissionSet.ts
- src/ldp/permissions/PermissionsExtractor.ts
- src/server/HttpHandler.ts
- src/server/HttpRequest.ts
- src/server/HttpResponse.ts
- src/util/AsyncHandler.ts
This includes the relevant auth headers and a simplification of several others.
The PermissionsExtractor was added after we discovered nothing in the architecture yet covered getting the required permissions from an incoming HttpRequest.
There is no interface yet for the ResponseWriter because I'm not 100% sure yet what the input would be for that yet.
> feat: add additional supported interfaces

- .eslintrc.js
- package-lock.json
- package.json
- src/authentication/SimpleCredentialsExtractor.ts
- src/authorization/SimpleAuthorizer.ts
- src/ldp/AuthenticatedLdpHandler.ts
- src/ldp/http/ResponseWriter.ts
- src/ldp/http/SimpleResponseWriter.ts
- src/ldp/operations/OperationHandler.ts
- src/ldp/operations/ResponseDescription.ts
- src/ldp/operations/SimpleDeleteOperationHandler.ts
- src/ldp/operations/SimpleGetOperationHandler.ts
- src/ldp/operations/SimplePostOperationHandler.ts
- src/ldp/permissions/SimplePermissionsExtractor.ts
- src/server/HttpResponse.ts
- src/storage/SimpleResourceStore.ts
- src/util/errors/NotFoundHttpError.ts
- test/integration/AuthenticatedLdpHandler.test.ts
- test/unit/authentication/SimpleCredentialsExtractor.test.ts
- test/unit/authorization/SimpleAuthorizer.test.ts
- test/unit/ldp/AuthenticatedLdpHandler.test.ts
- test/unit/ldp/http/SimpleResponseWriter.test.ts
- test/unit/ldp/operations/SimpleDeleteOperationHandler.test.ts
- test/unit/ldp/operations/SimpleGetOperationHandler.test.ts
- test/unit/ldp/operations/SimplePostOperationHandler.test.ts
- test/unit/ldp/permissions/SimplePermissionsExtractor.test.ts
- test/unit/storage/SimpleResourceStore.test.ts
With this pull request simple implementations are added, thereby allowing a full integration test starting at the ldp handler.
There is another ugly N3 cast which should also be fixed after changing the typing definitions.
ResponseDescription was added as an interface, representing the response that needs to be written back to the user. Currently this contains the identifier and optionally a body, but more would be needed to have a correct status code for example. This situation is actually similar to the problem with the errors. So here it could also be an option to encode the status code into the ResponseDescription. Or to instead embed the HTTP verb that was used and let the ResponseWriter do the conversion.
Another issue is who exactly would be responsible with generating a text/turle …
> Add simple implementations of all interfaces

- bin/server.ts
- index.ts
- package-lock.json
- package.json
- src/ldp/http/SimpleTargetExtractor.ts
- src/server/ExpressHttpServer.ts
- src/storage/SimpleResourceStore.ts
- src/util/Util.ts
- test/integration/AuthenticatedLdpHandler.test.ts
- test/integration/RequestParser.test.ts
- test/unit/ldp/http/SimpleTargetExtractor.test.ts
- test/unit/server/ExpressHttpServer.test.ts
- test/unit/storage/SimpleResourceStore.test.ts
- tsconfig.json
This allows setting up the (very basic) Solid server using `node bin/server.js` (with optionally `-p port`). Until there is dependency injection this class also handles the linking of all the classes.
I looked into Koa and the implementation would pretty much be 100% the same due to so little express code being used. Since there already was a dependency on express through another dependency I went for that one.
Some changes from the architecture:
- The constructor takes a single handler instead of an array. Currently didn't see the point of an array if we have `CompositeAsyncHandler`.
- The `listen` function returns an `http.Server`, makes testing much easier and makes it more similar to the actual `listen` interface of `http.Server`.
Currently CORS is handled in the new server class. An …
> Set up server using express

- bin/server.ts
- index.ts
- package-lock.json
- package.json
- src/ldp/http/Patch.ts
- src/ldp/http/SimpleSparqlUpdateBodyParser.ts
- src/ldp/http/SparqlUpdatePatch.ts
- src/ldp/operations/SimplePatchOperationHandler.ts
- src/storage/PatchingStore.ts
- src/storage/patch/PatchHandler.ts
- src/storage/patch/SimpleSparqlUpdatePatchHandler.ts
- src/util/Util.ts
- test/integration/AuthenticatedLdpHandler.test.ts
- test/unit/ldp/http/SimpleSparqlUpdateBodyParser.test.ts
- test/unit/ldp/operations/SimplePatchOperationHandler.test.ts
- test/unit/storage/PatchingStore.test.ts
- test/unit/storage/patch/SimpleSparqlUpdatePatchHandler.test.ts
This adds support for SPARQL updates through PATCH requests. Currently only deletes/inserts without variables are supported (will need to look into an internal querying engine potentially for more advanced queries).
The main "special" thing is probably how the input body is handled in a Patch. To prevent multiple parsings, the body parser immediately reads the body and parses it into the algebra. The data field then throws an error if it would still be accessed afterwards (which should never happen since every class that uses a Patch would know of the interface). This was already somewhat discussed with @RubenVerborgh but this can still change of course.
> SPARQL updates

- bin/server.ts
- src/authentication/Credentials.ts
- src/authentication/SimpleCredentialsExtractor.ts
- src/ldp/AuthenticatedLdpHandler.ts
- src/ldp/http/AcceptPreferenceParser.ts
- src/ldp/http/BodyParser.ts
- src/ldp/http/ResponseWriter.ts
- src/ldp/http/SimpleBodyParser.ts
- src/ldp/http/SimpleRequestParser.ts
- src/ldp/http/SimpleResponseWriter.ts
- src/ldp/operations/SimplePostOperationHandler.ts
- src/server/ExpressHttpServer.ts
- src/storage/patch/SimpleSparqlUpdatePatchHandler.ts
- src/util/errors/HttpError.ts
- src/util/errors/UnsupportedHttpError.ts
- test/integration/AuthenticatedLdpHandler.test.ts
- test/integration/RequestParser.test.ts
- test/unit/authentication/SimpleCredentialsExtractor.test.ts
- test/unit/ldp/AuthenticatedLdpHandler.test.ts
- test/unit/ldp/http/SimpleBodyParser.test.ts
- test/unit/ldp/http/SimpleRequestParser.test.ts
- test/unit/ldp/http/SimpleResponseWriter.test.ts
- test/unit/ldp/operations/SimplePostOperationHandler.test.ts
- test/unit/storage/LockingResourceStore.test.ts
- test/unit/storage/PatchingStore.test.ts
- test/unit/storage/SimpleResourceStore.test.ts
- test/unit/storage/patch/SimpleSparqlUpdatePatchHandler.test.ts
- tsconfig.json
Sets TypeScript to strict
Biggest changes:
* I made the `webId` field in `Credentials` optional. This way the `CredentialsExtractor` always returns a `Credentials` object, even if no credentials were found. (Instead of returning undefined in that case).
* `BodyParser` now returns `Representation | undefined`. Not convinced that this is the best solution, but it is what is needed for now since the `SimpleBodyParser` also handles the case of there being no body. Perhaps this should be caught in the `RequestParser` instead. Related to #8 .
* There are some cases where a check that was in the `canHandle` function was needed again in the `handle` function to prevent accessing potential `undefined` data since some input fields are optional. E.g. the method field in a `HttpRequest`. Another …
> fix: Enable strict TypeScript settings

- bin/server.ts
- index.ts
- src/authorization/AclConstants.ts
- src/authorization/AclManager.ts
- src/authorization/SimpleAclAuthorizer.ts
- src/authorization/SimpleExtensionAclManager.ts
- src/ldp/operations/SimplePutOperationHandler.ts
- src/ldp/permissions/PermissionSet.ts
- src/ldp/permissions/SimplePermissionsExtractor.ts
- src/storage/ContainerManager.ts
- src/storage/SimpleResourceStore.ts
- src/storage/UrlContainerManager.ts
- src/util/errors/ForbiddenHttpError.ts
- src/util/errors/UnauthorizedHttpError.ts
- test/index.ts
- test/integration/AuthenticatedLdpHandler.test.ts
- test/integration/Authorization.test.ts
- test/unit/authorization/SimpleAclAuthorizer.test.ts
- test/unit/authorization/SimpleExtensionAclManager.test.ts
- test/unit/ldp/operations/SimpleDeleteOperationHandler.test.ts
- test/unit/ldp/operations/SimplePutOperationHandler.test.ts
- test/unit/ldp/permissions/SimplePermissionsExtractor.test.ts
- test/unit/server/ExpressHttpServer.test.ts
- test/unit/storage/UrlContainerManager.test.ts
- test/util/Util.ts
Only depends on #48 for integration, so first 3 commits here are irrelevant.
Adds support for most acl options, except groups and origin.
I added two new interfaces:
* `AclManager` which is responsible for determining where the acl files are located.
* `ContainerManager` which determines what the container is of a resource.
I'm expecting the ContainerManager interface to be extended in the future once we realize some more functions we need related to containers.
When starting the server a new acl file gets created at the root that gives everyone all permissions since it is required to have an acl file at root now.
> Add acl support

- src/storage/LockingResourceStore.ts
- test/unit/storage/LockingResourceStore.test.ts
- test/unit/storage/SingleThreadedResourceLocker.test.ts
Closes #41
It will only release the lock on a getRepresentation when the Readable stream has ended reading data or when an error occurs.
The timeout mechanism has not yet been implemented in this PR.
> fix: Release lock only when stream ends or is abandoned

- bin/server.ts
- index.ts
- src/init/Setup.ts
- test/unit/init/Setup.test.ts
This is a requirement for enabling dependency injection.
ACL init will likely change in the future, but other things may be added in this setup component in the future.
> Move ACL init into dedicated Setup component

- src/storage/SimpleResourceStore.ts
We should at some point change this class to be a correct ResourceStore, but for now this at least allows GET requests to root to not fail.
> fix: Give SimpleResourceStore root a content-type

- src/ldp/http/SimpleBodyParser.ts
- test/integration/RequestParser.test.ts
- test/unit/ldp/http/SimpleBodyParser.test.ts
This is more of a hotfix than a feature, since I was planning on fully looking into the metadata parsing when #65 was merged. But since we currently have people working on the integration tests and having these two headers in the metadata is quite important for testing the FileResourceStore this would allow that work to continue there until an actual metadata parser was made.
> feat: Support link and slug headers in SimpleBodyParser

- src/init/RuntimeConfig.ts
- src/storage/UrlContainerManager.ts
- test/unit/init/RuntimeConfig.test.ts
Some small cleanup work to normalize `base` in `RuntimeConfig`, and allow variants to be retrieved.
> Move base normalization to RuntimeConfig

- bin/server.ts
- index.ts
- package-lock.json
- package.json
- src/storage/conversion/RdfToQuadConverter.ts
- test/unit/storage/conversion/RdfToQuadConverter.test.ts
A simple addition that allows us to automatically parse all major RDF formats: https://github.com/rubensworks/rdf-parse.js#rdf-parse
> Add support for parsing more RDF formats using rdf-parse

- README.md
No rocket science, just some simple getting started examples with `curl`.
> docs: explain supported HTTP methods in README

- package.json
Also tested the bin, and everything seems to be working.
We should reserve some time to check and see if this also still works after publishing. Since it works with `npm link` without problems, I don't expect major issues here.
Closes #93
> change: set bin name to community-solid-server

- README.md
- config/presets/storage_wrapper.json
- index.ts
- package-lock.json
- package.json
- src/storage/conversion/QuadToRdfConverter.ts
- test/unit/storage/conversion/QuadToRdfConverter.test.ts
A simple addition that allows serialization to all N3.js formats an JSON-LD.
Once we add more formats to Comunica, they will also automatically be included here.
> Add generic QuadToRdfConverter

- .travis.yml
- package.json
Just a small addition that ensures our default config is always valid.
> change: validate config in precommit and in CI

- config/presets/storage_wrapper.json
- index.ts
- package.json
- src/storage/conversion/ChainedConverter.ts
- src/storage/conversion/QuadToRdfConverter.ts
- src/storage/conversion/RdfToQuadConverter.ts
- src/storage/conversion/TypedRepresentationConverter.ts
- test/integration/RepresentationConverter.test.ts
- test/unit/storage/conversion/ChainedConverter.test.ts
- test/unit/storage/conversion/QuadToRdfConverter.test.ts
- test/unit/storage/conversion/RdfToQuadConverter.test.ts
So I changed my mind and did make some sort of meta converter. This one is still sort of simple since you have to define what the intermadiate types are going to be (otherwise I would have to think about the best interface changes to request this information from the converters), but in practice this is going to cover most cases I think.
Haven't actually tested it with real converters yet, wanted to first check out the other PR with the new converter for that.
> feat: Create RepresentationConverter that chains other converters

- src/ldp/operations/PutOperationHandler.ts
- test/unit/ldp/operations/PutOperationHandler.test.ts
When executing a bodyless `PUT` request, I would get:
```
UnsupportedHttpError: No handler supports the given input: [This handler only supports DELETE operations., This handler only supports GET operations., This handler only supports PATCH operations., This handler only supports POST operations., PUT operations require a body.].
at CompositeAsyncHandler.findHandler (/Users/ruben/Documents/UGent/Solid/solid-community-server/src/util/CompositeAsyncHandler.js:77:15)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Clearly, the `PUT` handler is the (only) right one. The fact that it errors is because the request is invalid, and the `PUT` handler is the only one who knows that.
So the right error is “no body specified”, all the rest is noise. This PR brings it to:
``` …
```
> Support all PUT operations, error later

- src/storage/InMemoryResourceStore.ts
- test/unit/storage/InMemoryResourceStore.test.ts
I don't want to say this is a complete solution to #127 , but this does remove all delay that was introduced by this store first buffering the response before sending it.
> fix: Don't buffer data before sending response with InMemoryResourceStore

- .eslintrc.js
- src/ldp/representation/RepresentationMetadata.ts
- src/storage/FileResourceStore.ts
- src/storage/patch/SparqlUpdatePatchHandler.ts
- src/util/MetadataController.ts
- test/unit/ldp/http/BasicResponseWriter.test.ts
- test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts
This also uses the new `import type` syntax for importing rdf-js types,
as it is required for making this new linter rule pass.
Closes #132
> lint: enable no-extraneous-dependencies rule

- .gitignore
- package.json
Since updating all the eslint dependencies (or just because we have more files, dunno), eslint has really been taking a lot of time for me. This should fix most of that. Doing this as PR because I'm not sure if there are any potential issues with eslint cache any of you are aware of? If not we'll see if this keeps working correctly.
> build: Add eslint cache

- src/util/CompositeAsyncHandler.ts
- src/util/errors/HttpError.ts
- src/util/errors/InternalServerError.ts
- test/unit/util/CompositeAsyncHandler.test.ts
Resolves #23 .
This does put some status code logic in the CompositeAsyncHandler but not sure how to do this otherwise since this is quite ingrained.
> fix: Retain status codes when combining errors

- src/ldp/http/BasicRequestParser.ts
- src/ldp/http/BasicResponseWriter.ts
- src/ldp/http/BasicTargetExtractor.ts
- src/ldp/http/RawBodyParser.ts
- src/ldp/http/SparqlUpdateBodyParser.ts
- src/ldp/operations/PostOperationHandler.ts
- src/storage/conversion/ChainedConverter.ts
- src/util/ContentTypes.ts
- test/unit/ldp/http/BasicRequestParser.test.ts
- test/unit/ldp/http/BasicTargetExtractor.test.ts
- test/unit/ldp/operations/PostOperationHandler.test.ts
Resolves #119 .
Also cleaned up some canHandle functions.
IMO it's not always clearcut when something should be in `canHandle` or `handle`, but this should solve the more clear cases.
> fix: Have AsyncHandlers only check what is necessary

- config/presets/ldp/operation-handler.json
- index.ts
- src/ldp/operations/HeadOperationHandler.ts
- test/configs/Util.ts
- test/unit/ldp/operations/HeadOperationHandler.test.ts
This closes #85.
~~I have not yet managed to fully cover the code in the `process.nextTick` in `HeadOperationHandler#30`.
An explicit expect to see that it's an empty Readable didn't work either, because jest expects a Readable for some reason, but gets an Object with the same content.~~
> Implement HEAD request support

- src/ldp/http/BasicTargetExtractor.ts
- src/storage/ExtensionBasedMapper.ts
- src/storage/FileIdentifierMapper.ts
- src/storage/FileResourceStore.ts
- src/util/Util.ts
- test/unit/ldp/http/BasicTargetExtractor.test.ts
- test/unit/storage/ExtensionBasedMapper.test.ts
- test/unit/storage/FileResourceStore.test.ts
- test/unit/util/Util.test.ts
This resolves #150 and part of #151. 
It does not handle #146 yet. That would require more changes in the file store which is not the focus of this PR (and I don't want to do many changes there until #167 is handled).
Several changes were necessary in the file store and the file store tests (some of the mocks broke since the `fs` calls aren't in the same order anymore), but the main thing to look at is what happens in the `ExtensionBasedMapper`.
It is not fully yet as I would want it. It should only have the 2 public functions from the interface, but some of the other public functions would require more drastic changes to the file store to remove, for which I refer to my comment above.
> feat: Have ExtensionBasedMapper handle extensions correctly

- config/config-default.json
- config/presets/ldp/metadata-handler.json
- config/presets/ldp/request-parser.json
- index.ts
- src/ldp/http/AcceptPreferenceParser.ts
- src/ldp/http/BasicRequestParser.ts
- src/ldp/http/BodyParser.ts
- src/ldp/http/RawBodyParser.ts
- src/ldp/http/SparqlUpdateBodyParser.ts
- src/ldp/http/metadata/BasicMetadataExtractor.ts
- src/ldp/http/metadata/ContentTypeParser.ts
- src/ldp/http/metadata/LinkTypeParser.ts
- src/ldp/http/metadata/MetadataExtractor.ts
- src/ldp/http/metadata/MetadataParser.ts
- src/ldp/http/metadata/SlugParser.ts
- src/util/HeaderUtil.ts
- test/configs/BasicHandlersConfig.ts
- test/configs/FileResourceStoreConfig.ts
- test/configs/Util.ts
- test/integration/RequestParser.test.ts
- test/unit/ldp/http/BasicRequestParser.test.ts
- test/unit/ldp/http/RawBodyParser.test.ts
- test/unit/ldp/http/SparqlUpdateBodyParser.test.ts
- test/unit/ldp/http/metadata/BasicMetadataExtractor.test.ts
- test/unit/ldp/http/metadata/ContentTypeParser.test.ts
- test/unit/ldp/http/metadata/LinkTypeParser.test.ts
- test/unit/ldp/http/metadata/SlugParser.test.ts
- test/unit/util/HeaderUtil.test.ts
Resolves #75 .
Since we now have decent metadata support, we still need a clean way to put the incoming metadata in there. So this is my suggestion for it.
Note that for the MetadataParsers their functionality is similar to AsyncHandlers but I used a new interface since the contracts is slightly different (it's no problem if they can't handle it, and all parsers should be executed regardless of the result of others).
> Add a metadata parser

- src/storage/DataAccessorBasedStore.ts
- src/storage/ExtensionBasedMapper.ts
- src/storage/accessors/FileDataAccessor.ts
- test/unit/storage/accessors/FileDataAccessor.test.ts
- test/unit/storage/accessors/InMemoryDataAccessor.test.ts
Resolves #146 .
Makes sure to update the file path if the content-type gets updated and makes the metadata paths be independent of the content-type.
Also renamed all references from "data resource" to "document" for consistency.
> feat: Fully support storing content-type in file extensions

- src/authentication/UnsecureWebIdExtractor.ts
- src/authorization/AllowEverythingAuthorizer.ts
- src/authorization/WebAclAuthorizer.ts
- src/ldp/http/AcceptPreferenceParser.ts
- src/ldp/http/BasicRequestParser.ts
- src/ldp/http/BasicTargetExtractor.ts
- src/ldp/http/RawBodyParser.ts
- src/ldp/http/metadata/BasicMetadataExtractor.ts
- src/util/AsyncHandler.ts
- test/unit/authentication/UnsecureWebIdExtractor.ts
- test/unit/authorization/AllowEverythingAuthorizer.test.ts
- test/unit/authorization/WebAclAuthorizer.test.ts
- test/unit/ldp/http/AcceptPreferenceParser.test.ts
- test/unit/ldp/http/BasicRequestParser.test.ts
- test/unit/ldp/http/BasicTargetExtractor.test.ts
- test/unit/ldp/http/RawBodyParser.test.ts
- test/unit/ldp/http/metadata/BasicMetadataExtractor.test.ts
- test/unit/server/ExpressHttpServer.test.ts
- test/unit/util/AsyncHandler.test.ts
Saves some lines; unless we think that being explicit is nicer.
> Implement empty canHandle on base class

- src/ldp/representation/RepresentationPreference.ts
- src/storage/RepresentationConvertingStore.ts
- src/storage/conversion/ConversionUtil.ts
- src/util/ContentTypes.ts
- test/unit/storage/RepresentationConvertingStore.test.ts
- test/unit/storage/conversion/ConversionUtil.test.ts
This closes #306 and closes #276 . It does not yet resolve the issue of making sure the patching store does not send quads back to the file store, but that should just be a config change after #297 is resolved.
I like how we can now reject content-types using weight 0, not a big fan of how there is now just a line always adding this preference in `AcceptPreferenceParser`, but it seemed like the best place to add it. Could also add an input parameter taking forbidden content-types into account but that seems a bit overkill.
> Make internal/quads unacceptable as output format

- src/ldp/http/BasicResponseWriter.ts
- src/ldp/http/SparqlUpdateBodyParser.ts
- src/storage/conversion/RdfToQuadConverter.ts
- src/util/MetadataController.ts
- src/util/Util.ts
- test/unit/ldp/http/BasicResponseWriter.test.ts
- test/unit/util/Util.test.ts
Initially I wanted to use `stream.pipeline` in `pipeStreamsAndErrors` but that still doesn't consistently emit error events so I didn't use it in the end.
Also closes #116 (and closes #310) due to the changes in the response writer.
> refactor: Make piping consistent

- config/presets/storage-wrapper.json
- index.ts
- src/storage/ExpiringLock.ts
- src/storage/ExpiringResourceLocker.ts
- src/storage/LockingResourceStore.ts
- src/storage/ResourceLocker.ts
- src/storage/WrappedExpiringLock.ts
- src/storage/WrappedExpiringResourceLocker.ts
- test/unit/storage/LockingResourceStore.test.ts
- test/unit/storage/WrappedExpiringResourceLocker.test.ts
Closes #62.
I'm not sure if this is what is wanted, so feedback is welcome.
The `READ_TIMEOUT` variable could also be given to the acquire function but for now I have kept it the same as the current implementation.
I had to make some adjustments to the tests and for example, in the tests where the lock has to be time-out, I dropped the order check because here the real implementation was used for acquire and release so they could not be logged in the order list. If that would be a problem anyway, I can see if there is a way to check it anyway.
> feat: Add heartbeat/expiring to locks

- src/ldp/UnsecureWebSocketsProtocol.ts
- src/ldp/http/BasicTargetExtractor.ts
- src/ldp/http/metadata/WebSocketMetadataWriter.ts
- test/unit/ldp/http/BasicTargetExtractor.test.ts
- test/unit/ldp/http/metadata/LinkRelMetadataWriter.test.ts
- test/unit/ldp/http/metadata/MappedMetadataWriter.test.ts
- test/unit/ldp/http/metadata/WebSocketMetadataWriter.test.ts
This is the last individual piece for WebSocket support; the final one is wiring them up in the configuration.
The second commit aligns some of the other code; I found some minor shortcomings when looking for related code that could inform the writing of the `WebSocketMetadataWriter` class.
> Advertise WebSocket via Updates-Via header

- componentsjs-generator-ignore-classes.json
- config/presets/ldp.json
- config/presets/ldp/request-parser.json
- package-lock.json
- package.json
I upgraded but am now getting:
```
> @solid/community-server@0.2.0 build:components /Users/ruben/Documents/UGent/Solid/solid-community-server
> componentsjs-generator -s src
Failed to load super class HttpError of ConflictHttpError in /Users/ruben/Documents/UGent/Solid/solid-community-server/src/util/errors/ConflictHttpError:
Failed to load super class Error of HttpError in /Users/ruben/Documents/UGent/Solid/solid-community-server/src/util/errors/ConflictHttpError:
Could not load class Error from /Users/ruben/Documents/UGent/Solid/solid-community-server/src/util/errors/HttpError
```
So there seems to be a problem with built-in JavaScript classes.
> Update componentsjs-generator to v1.5.0

- src/init/Setup.ts
- src/ldp/http/response/OkResponseDescription.ts
- src/ldp/http/response/ResponseDescription.ts
- src/ldp/representation/Representation.ts
- src/server/ExpressHttpServerFactory.ts
- src/server/HttpRequest.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/LockingResourceStore.ts
- src/storage/accessors/DataAccessor.ts
- src/storage/accessors/FileDataAccessor.ts
- src/storage/accessors/InMemoryDataAccessor.ts
- src/storage/accessors/SparqlDataAccessor.ts
- src/storage/conversion/QuadToRdfConverter.ts
- src/storage/patch/SparqlUpdatePatchHandler.ts
- src/util/GuardedStream.ts
- src/util/QuadUtil.ts
- src/util/StreamUtil.ts
- test/integration/FullConfig.acl.test.ts
- test/integration/RepresentationConverter.test.ts
- test/unit/ldp/http/BasicResponseWriter.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
- test/unit/storage/accessors/FileDataAccessor.test.ts
- test/unit/storage/accessors/InMemoryDataAccessor.test.ts
- test/unit/storage/accessors/SparqlDataAccessor.test.ts
- test/unit/util/GuardedStream.test.ts
- test/unit/util/StreamUtil.test.ts
- test/util/TestHelpers.ts
This closes #317.
This is the other solution as mentioned in #326  (read that one first).
In this case a new utility function gets created which adds an error event listener to a stream to store that event. Then, if any new event listeners get added at a later point in time that stored event will be sent to the listener callback function just as if it happened at that point in time. This way Node.js buffering a stream and throwing an error before we attach a listener is not an issue. Buffering does not cause an "end" event to be fired early so we don't have to listen to that one in advance.
Similar to the monitor, a warning will be logged if an error event gets triggered but no listener gets added within a certain time.
This function should be called every time a new stream gets created …
> Wrap streams to catch errors

- .github/workflows/ci.yml
The initial commit is to test PRs from a remote fork. If CI runs successfully, just ignore this.
> Better CI support for GH Actions from remote forks

- .github/workflows/ci.yml
- src/ldp/http/SparqlUpdateBodyParser.ts
- src/storage/conversion/RdfToQuadConverter.ts
- test/unit/ldp/http/SparqlUpdateBodyParser.test.ts
We will need to drop Node 10, given that the crucial functionality of #358 transitively depends on `@panva/jose`, which only works on 12 and up.
Since Node 10 goes out of maintenance in April 2021, this seems acceptable.
> Drop Node 10 support

- config/config-default.json
- config/config-file.json
- config/config-path-routing.json
- config/config-rdf-to-sparql-endpoint.json
- config/config-sparql-endpoint.json
- config/presets/http.json
- config/presets/ldp.json
- config/presets/ldp/response-writer.json
- config/presets/middleware.json
- index.ts
- src/ldp/http/metadata/LinkRelMetadataWriter.ts
- src/ldp/http/metadata/MappedMetadataWriter.ts
- src/server/ExpressHttpServerFactory.ts
- src/server/middleware/CorsHandler.ts
- src/server/middleware/HeaderHandler.ts
- src/server/middleware/WebSocketAdvertiser.ts
- src/storage/routing/RegexRouterRule.ts
- test/configs/middleware.json
- test/configs/websockets.json
- test/integration/Middleware.test.ts
- test/integration/WebSocketsProtocol.test.ts
- test/unit/server/ExpressHttpServerFactory.test.ts
- test/unit/server/middleware/CorsHandler.test.ts
- test/unit/server/middleware/HeaderHandler.test.ts
- test/unit/server/middleware/WebSocketAdvertiser.test.ts
CORS and other middleware is currently hardwired inside of the Express server.
This makes it hard to configure them.
This PR makes each piece of middleware a separate component that can be configured with Components.js.
Additionally, this PR adjusts some of that configuration.
Closes https://github.com/solid/community-server/issues/27
> Separate middleware from Express

- src/ldp/UnsecureWebSocketsProtocol.ts
- src/ldp/http/BasicTargetExtractor.ts
- src/util/HeaderUtil.ts
- test/integration/WebSocketsProtocol.test.ts
- test/unit/ldp/UnsecureWebSocketsProtocol.test.ts
- test/unit/ldp/http/BasicTargetExtractor.test.ts
- test/unit/util/HeaderUtil.test.ts
Required when servers are behind a reverse proxy.
Closes https://github.com/solid/community-server/issues/22
> Support the Forwarded header

- src/storage/DataAccessorBasedStore.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
This prevents the container data check from throwing an error when converting to quads if the incoming data already is quads.
Related to #384 but only solves part of it.
> fix: Allow quad data for containers

- config/presets/acl.json
- config/presets/storage-wrapper.json
- config/presets/storage/backend/storage-filesystem.json
- config/presets/storage/backend/storage-memory.json
- config/presets/storage/backend/storage-sparql-endpoint.json
- src/authorization/WebAclAuthorizer.ts
- src/index.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/MonitoringStore.ts
- src/storage/accessors/SparqlDataAccessor.ts
- src/util/PathUtil.ts
- src/util/identifiers/IdentifierStrategy.ts
- src/util/identifiers/SingleRootIdentifierStrategy.ts
- test/configs/Util.ts
- test/integration/LockingResourceStore.test.ts
- test/integration/SparqlStorage.test.ts
- test/unit/authorization/WebAclAuthorizer.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
- test/unit/storage/MonitoringStore.test.ts
- test/unit/storage/accessors/SparqlDataAccessor.test.ts
- test/unit/util/PathUtil.test.ts
- test/unit/util/identifiers/SingleRootIdentifierStrategy.test.ts
Based on https://github.com/solid/community-server/issues/394#issuecomment-739805093
In preparation for some other issues where `isRootContainer` is needed.
I added the `toRelative` and `fromRelative` functions initially, but there are some problems with that interface so will have to rethink later. Pod provisioning would have same issues (which can be fixed I think, but I would prefer looking into that later).
> Re-introduce ContainerManager

- src/storage/accessors/SparqlDataAccessor.ts
- test/unit/storage/accessors/FileDataAccessor.test.ts
- test/unit/storage/accessors/SparqlDataAccessor.test.ts
Closes #410 . Didn't include tests for the memory store yet due to #417 but this part can already be merged.
> fix: Allow overwriting and deleting root container in SparqlDataAccessor 

- src/storage/accessors/InMemoryDataAccessor.ts
- src/storage/accessors/SparqlDataAccessor.ts
- test/unit/storage/accessors/FileDataAccessor.test.ts
- test/unit/storage/accessors/InMemoryDataAccessor.test.ts
- test/unit/storage/accessors/SparqlDataAccessor.test.ts
Closes #417 and brings the memory data accessor in line with the changes from #418
> fix: Allow deletion of root in InMemoryDataAccessor

- config/presets/init.json
- src/index.ts
- src/init/RootContainerInitializer.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/accessors/SparqlDataAccessor.ts
- src/util/UriConstants.ts
- test/configs/Util.ts
- test/integration/AuthenticatedLdpHandler.test.ts
- test/integration/Authorization.test.ts
- test/integration/FullConfig.acl.test.ts
- test/integration/FullConfig.noAuth.test.ts
- test/integration/LockingResourceStore.test.ts
- test/integration/PodCreation.test.ts
- test/integration/SparqlStorage.test.ts
- test/integration/WebSocketsProtocol.test.ts
- test/unit/init/RootContainerInitializer.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
- test/unit/storage/accessors/InMemoryDataAccessor.test.ts
- test/unit/storage/accessors/SparqlDataAccessor.test.ts
Depends on #418 and #419 .
Closes #412 (except that we perhaps still want to update this to PATCH in the future).
The change was easy to do (once the related issues were fixed), most of the work was updating the integration tests. Partially due to #305 but also because there are assumptions in the code that the root container is going to exist while only testing part of the code (and thus excluding the store initializer).
There is some overlap with the `AclInitializer` but it didn't seem necessary to generalize that part as these classes are quite simple. But something to think of if this paradigm occurs more times in the future.
> Create ResourceStoreInitializer for initializing root containers

- src/pods/generate/TemplatedResourcesGenerator.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/accessors/FileDataAccessor.ts
- templates/.meta
- test/unit/pods/generate/TemplatedResourcesGenerator.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
This opens up a lot more possibilities with the templates and will prevent random pod deletion after #426 .
This does encode what the metadata files should look like (content-type wise and extension) in the template generator, but generalizing that would cover most of the generator so probably would need a new class anyway if new template types should be supported.
> feat: Support .meta files for pod provisioning

- config/presets/http.json
- test/integration/Middleware.test.ts
Accidentally stumbled upon this when making #428 . Currently all requests to `/pods` will also be sent to the LDP handler.
As it currently is, the config for inserting the pod http handler in the config has always been wrong. It used to work because the `AllVoidCompositeHandler` used to ignore errors, but since the change to `SequenceHandler` it probably never worked anymore. Perhaps this also caused the confusion in #421 .
This does mean that the middleware will only run for requests that reach the LDP handler. If we want the middleware to always run more changes will be required.
Should also investigate how the pod creation integration test didn't catch this. Perhaps a timing issue because the pod handler managed to respond first.
> fix: Make default HttpHandler a WaterfallHandler

- src/storage/DataAccessorBasedStore.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
Depends on #424 .
Closes #411 .
Was going to also update the pod provisioning so they count as storage, but #341 should be resolved first so we have a cleaner way to handle metadata.
> fix: Prevent deletion of root storage containers

- package-lock.json
- package.json
- test/configs/Util.ts
- test/tsconfig.json
- tsconfig.json
It seems like an improvement to use a base tsconfig as per the TypeScript documentation:
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#tsconfig-bases
Note: I also ordered the compiler options alphabetically.
> Use base tsconfig

- config/presets/ldp/credentials-extractor.json
- package-lock.json
- package.json
- src/authentication/BearerWebIdExtractor.ts
- src/authentication/DPoPWebIdExtractor.ts
- src/index.ts
- test/unit/authentication/BearerWebIdExtractor.test.ts
- test/unit/authentication/DPoPWebIdExtractor.test.ts
I am missing something to adapt the credentials extractor waterfall handler, but otherwise should be good to go.
https://github.com/solid/community-server/blob/master/config/presets/ldp/credentials-extractor.json
> feat: Bearer token support

- .eslintignore
- .gitignore
- package.json
It feels like everything that is versioned and supported by ESLint should be linted and everything that isn't versioned shouldn't be linted.
Hence, I feel like the .eslintignore is mostly redundant.
I ordered alphabetically .gitignore and base ESLint ignore on it.
> refactor: ESLint ignore

- src/storage/DataAccessorBasedStore.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
Fixes #456 . As added bonus it also results in you being able to give a folder that doesn't exist as CLI param and it will be created (no nested folders though).
This still has the `hasSlash` variable there. Could have renamed it to something else but 2 lines below we are actually changing the slashes so it makes sense to me. The slash logic has to stay because it's part of the spec: 
> If two URIs differ only in the trailing slash, and the server has associated a resource with one of them, then the other URI MUST NOT correspond to another resource.
The only way to remove that logic from the store would be to move the entire function (or most parts of it) to the IdentifierStrategy but I think that makes less sense.
> fix: Don't get normalized metadata for root containers

- .componentsignore
- src/index.ts
- src/init/AclInitializer.ts
- src/init/RootContainerInitializer.ts
- src/ldp/http/RawBodyParser.ts
- src/ldp/representation/BasicRepresentation.ts
- src/ldp/representation/RepresentationMetadata.ts
- src/pods/generate/TemplatedResourcesGenerator.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/conversion/ContentTypeReplacer.ts
- src/storage/conversion/QuadToRdfConverter.ts
- src/storage/conversion/RdfToQuadConverter.ts
- src/storage/patch/SparqlUpdatePatchHandler.ts
- src/util/GuardedStream.ts
- src/util/StreamUtil.ts
- test/integration/LdpHandlerWithAuth.test.ts
- test/integration/LockingResourceStore.test.ts
- test/integration/RepresentationConverter.test.ts
- test/unit/ldp/http/BasicResponseWriter.test.ts
- test/unit/ldp/representation/BasicRepresentation.test.ts
- test/unit/ldp/representation/RepresentationMetadata.test.ts
- test/unit/pods/GeneratedPodManager.test.ts
- test/unit/pods/agent/AgentJsonParser.test.ts
- test/unit/storage/RepresentationConvertingStore.test.ts
- test/unit/storage/accessors/FileDataAccessor.test.ts
- test/unit/storage/accessors/InMemoryDataAccessor.test.ts
- test/unit/storage/conversion/ChainedConverter.test.ts
- test/unit/storage/conversion/QuadToRdfConverter.test.ts
- test/unit/storage/conversion/RdfToQuadConverter.test.ts
- test/util/TestHelpers.ts
I noticed that `RepresentationMetadata` was often instantiated with just a content type, so I added a shortcut for this.
This allowed me to introduce `BasicRepresentation` as a convenience constructor.
> Add new metadata and representation constructors

- src/util/GuardedStream.ts
- test/integration/GuardedStream.test.ts
- test/unit/util/GuardedStream.test.ts
Fixes #462 
Based on https://github.com/solid/community-server/pull/462#issuecomment-758013492
The test in the first commit fails before doing the changes in the second commit.
This solution works and all tests pass, but now I get some of these errors when running the integrations tests:
```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.
at Function.get (node_modules/logform/index.js:28:14)
at WinstonLoggerFactory.createLogger (src/logging/WinstonLoggerFactory.ts:283:32)
at LazyLogger.log (src/logging/LazyLogger.ts:290:58)
at LazyLogger.error (src/logging/Logger.ts:322:17)
at Timeout._onTimeout (src/util/GuardedStream.ts:33:24)
```
Which seems to imply that the guarded stream is now trying to log errors that are not being listened to. So …
> Fix problem with guarded streams still throwing async errors

- src/authorization/AclManager.ts
- src/authorization/WebAclAuthorizer.ts
- src/init/AclInitializer.ts
- src/init/RootContainerInitializer.ts
- src/ldp/operations/PatchOperationHandler.ts
- src/ldp/operations/PostOperationHandler.ts
- src/ldp/operations/PutOperationHandler.ts
- src/server/middleware/CorsHandler.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/accessors/DataAccessor.ts
- src/storage/patch/SparqlUpdatePatchHandler.ts
- src/util/PathUtil.ts
- test/unit/authorization/WebAclAuthorizer.test.ts
- test/unit/ldp/operations/PatchOperationHandler.test.ts
- test/unit/ldp/operations/PostOperationHandler.test.ts
- test/unit/ldp/operations/PutOperationHandler.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
I went through the Solid spec to add references to all relevant parts in the code. This included making some minor changes here and there to be fully compliant to some parts, also fixes #480 .
The code changes are:
* Changing some of the errors being thrown in `DataAccesorBasedStore` and streamlining some of the behaviour there.
* Checking for content-type in the POST/PUT/PATCH operation handlers.
* Changing an error in the acl handler.
There are some duplicate quotes in `DataAccessorBasedStore` since some general quotes are sometimes relevant in multiple places, but it seemd ok to me since this is the class that does a large part of the behaviour interactions.
What might be more interesting is the list of things we're not compliant with, I'm going to make an issue for that later so it …
> Add Solid spec references + minor fixes

- package-lock.json
- package.json
Updated https://github.com/solid/identity-token-verifier to be lenient on the [presence of the required](https://solid.github.io/authentication-panel/solid-oidc/#tokens-access) `client_id` claim in access tokens as it is not widely implemented in the Solid identity providers as of now.
See also: https://github.com/solid/identity-token-verifier/commit/ffa9ad4b04abdb43ae4cc6e63670a38c78789472
> fix: Token verification lenient on client_id

- config/presets/representation-conversion.json
- src/index.ts
- src/storage/RepresentationConvertingStore.ts
- src/storage/conversion/IfNeededConverter.ts
- src/storage/conversion/PassthroughConverter.ts
- test/unit/storage/RepresentationConvertingStore.test.ts
- test/unit/storage/conversion/IfNeededConverter.test.ts
- test/unit/storage/conversion/PassthroughConverter.test.ts
This simplifies the `RepresentationConvertingStore` by:
- moving out the decision logic of whether to convert
- ensuring there is always a converter, such that it does not need to be called conditionally
This also makes is possible to reuse the decision logic in other contexts where we will need content negotiation, such as for example error responses.
Note that usage of `IfNeededConverter` in the default configuration might become unnecessary with #484.
> Add IfNeededConverter and PassthroughConverter

- jest.config.js
- jest.coverage.config.js
- package.json
- test/unit/init/CliRunner.test.ts
Collect coverage by default, but only set the thresholds when running `test:unit`.
I ran into the issue where I often tested single test files if I'm working on a single class, but I also wanted to see if the coverage for tha class remained at 100%. This also sometimes caused jest to cache the results without coverage which would create issues when running the full tests if I didn't clear the jest cache.
I never actually use `test:watch` so not sure if it should also be added there. Not sure what the use case is for that one.
> test: Always collect coverage

- test/integration/Config.ts
[As requested](https://github.com/solid/community-server/pull/505#discussion_r557305834), part of the Components.js components manager is cached during integration tests.
This makes tests a couple of seconds faster on my machine.
> test: cache moduleState in integration tests to reduce exec time

- src/init/CliRunner.ts
- src/util/PathUtil.ts
- test/unit/init/CliRunner.test.ts
- test/unit/util/PathUtil.test.ts
Fixes #524
I kept the same naming conventions as the other functions, but it is sort of a misnomer to call the results of `windowsToPosixPath` POSIX paths, as `posix.isAbsolute` is still going to return false on those paths. So perhaps we should change that.
> fix: Accept absolute paths in CliRunner

- src/storage/mapping/FixedContentTypeMapper.ts
- test/unit/storage/mapping/FixedContentTypeMapper.test.ts
This allows configuring URLs in the form of `http://abc.ttl` to be mapped to file paths `file://abc.nq`.
> Add optional path and url suffixes to FixedContentTypeMapper

- config/presets/representation-conversion.json
- src/index.ts
- src/storage/conversion/ConstantConverter.ts
- src/storage/conversion/ConversionUtil.ts
- src/storage/conversion/IfNeededConverter.ts
- src/util/UnsupportedAsyncHandler.ts
- test/unit/storage/conversion/ConstantConverter.test.ts
- test/unit/storage/conversion/IfNeededConverter.test.ts
- test/unit/util/UnsupportedAsyncHandler.test.ts
This is part of https://github.com/solid/community-server/issues/510
When you request a resource from NSS in the browser, you get back an HTML page (that in turn then fetches another representation).
This PR adds a converter that enables this functionality.
It is not enabled by default (as this would make testing a horror), but you can try it with a config such as:
```json
{
"@id": "urn:solid-server:default:RepresentationConverter",
"@type": "WaterfallHandler",
"WaterfallHandler:_handlers": [
{
"@type": "ConstantConverter",
"ConstantConverter:_contentType": "text/html",
"ConstantConverter:_filePath": "/Users/ruben/Documents/UGent/Solid/mashlib/dist/browse.html"
},
{ "@type": "IfNeededConverter" },
{ "@id": "urn:solid-server:default:ContentTypeReplacer" },
{ "@id": …
```
> Add functionality to serve a default index file

- src/authorization/WebAclAuthorizer.ts
- src/ldp/AuthenticatedLdpHandler.ts
- src/ldp/http/BasicResponseWriter.ts
- src/ldp/http/ErrorResponseWriter.ts
- src/ldp/http/SparqlUpdateBodyParser.ts
- src/pods/PodManagerHttpHandler.ts
- src/server/ExpressHttpServerFactory.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/RoutingResourceStore.ts
- src/storage/StoreUtil.ts
- src/storage/accessors/InMemoryDataAccessor.ts
- src/storage/accessors/SparqlDataAccessor.ts
- src/storage/patch/SparqlUpdatePatchHandler.ts
- src/util/WaterfallHandler.ts
- src/util/errors/BadRequestHttpError.ts
- src/util/errors/ConflictHttpError.ts
- src/util/errors/ErrorUtil.ts
- src/util/errors/ForbiddenHttpError.ts
- src/util/errors/HttpError.ts
- src/util/errors/InternalServerError.ts
- src/util/errors/MethodNotAllowedHttpError.ts
- src/util/errors/NotFoundHttpError.ts
- src/util/errors/NotImplementedHttpError.ts
- src/util/errors/UnauthorizedHttpError.ts
- src/util/errors/UnsupportedMediaTypeHttpError.ts
- test/unit/util/errors/HttpError.test.ts
Closes #464.
I looked into having a fancy static typing solution so only 1 instance of the function had to be written, but all solutions I found had typing issues or got way too extensive for something that is just a simple change so I kept it simple in the end.
Also includes an extra unit test to make sure our errors actually have the correct status codes.
> fix: Remove all instanceof checks

- config/presets/ldp/request-parser.json
- src/ldp/http/OriginalUrlExtractor.ts
- src/util/PathUtil.ts
- test/integration/LdpHandlerWithoutAuth.test.ts
- test/unit/ldp/http/OriginalUrlExtractor.test.ts
- test/unit/util/PathUtil.test.ts
- test/util/TestHelpers.ts
- test/util/Util.ts
Interesting case where LDP and https://github.com/solid/community-server/pull/502 diverge
> Ignore query string when extracting LDP target

- src/server/util/BasicOnErrorHttpHandler.ts
Fixes: https://github.com/solid/community-server/issues/586
Can't write after stream is ended/end it twice.
> fix: IdP crashes if interaction ID doesn't exist

- src/storage/conversion/ConversionUtil.ts
- src/storage/conversion/IfNeededConverter.ts
- test/unit/storage/conversion/ConversionUtil.test.ts
- test/unit/storage/conversion/IfNeededConverter.test.ts
Closes #593.
This was a special combination of `IfNeedBeConverter` not calling `matchingMediaTypes` if there are no preferences, and our failsafe against sending internal types in `matchingMediaTypes` not triggering in case there are no preferences.
> fix: Fixed bug with empty Accept headers and internal/quads bodies

- config/presets/storage-wrapper.json
- src/index.ts
- src/storage/LockingResourceStore.ts
- src/storage/keyvalue/JsonResourceStorage.ts
- src/storage/keyvalue/KeyValueStorage.ts
- src/storage/keyvalue/MemoryMapStorage.ts
- src/storage/keyvalue/ResourceIdentifierStorage.ts
- src/util/locking/EqualReadWriteLocker.ts
- src/util/locking/ExpiringReadWriteLocker.ts
- src/util/locking/GreedyReadWriteLocker.ts
- src/util/locking/ReadWriteLocker.ts
- src/util/locking/ResourceLocker.ts
- src/util/locking/SingleThreadedResourceLocker.ts
- src/util/locking/WrappedExpiringReadWriteLocker.ts
- test/integration/LockingResourceStore.test.ts
- test/unit/storage/LockingResourceStore.test.ts
- test/unit/storage/keyvalue/JsonResourceStorage.test.ts
- test/unit/storage/keyvalue/MemoryMapStorage.test.ts
- test/unit/storage/keyvalue/ResourceIdentifierStorage.test.ts
- test/unit/util/locking/EqualReadWriteLocker.test.ts
- test/unit/util/locking/GreedyReadWriteLocker.test.ts
- test/unit/util/locking/SingleThreadedResourceLocker.test.ts
- test/unit/util/locking/WrappedExpiringReadWriteLocker.test.ts
Closes #32, closes #542 .
First off, there are still some potential issues with this solution for which I'm not sure if we already have the parts in place to fix them all, more on this below.
Since we now have a read/write interface for our lockers, it should be possible to actually implement a locker that handles those locks differently. The only locking mechanism we currently have is the single threaded one with one kind of lock. I partially returned to the interface of having 1 type of lock, but in such a way that the actual lock is not exposed. This way this interface can also be used by multi-threaded locking solutions, such as a lockfile solution. The idea would then be that we could have read/write locking algorithms independent of the locking mechanism being used in the backend. …
> Implement actual read/write locking algorithm

- src/storage/DataAccessorBasedStore.ts
- src/storage/accessors/FileDataAccessor.ts
- src/storage/accessors/InMemoryDataAccessor.ts
- test/integration/Config.ts
- test/integration/LdpHandlerWithAuth.test.ts
- test/integration/LdpHandlerWithoutAuth.test.ts
- test/integration/LpdHandlerOperations.test.ts
- test/integration/WebSocketsProtocol.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
Closes #608
I was wrong in the issue, this probably never worked as I forgot to remove the default container from the memory store when doing the other root-related changes.
Also required changes in some tests which depended on that container being there.
Accidentally discovered a minor bug in the `DataAccessorBasedStore` when PUTting a resource if there is no root container (which in practice we would never see because of the initializer).
> Remove default root container in memory DataAccessor + minor fixes

- src/identity/interaction/email-password/handler/EmailPasswordRegisterHandler.ts
- src/identity/interaction/util/BasicIssuerReferenceWebIdOwnershipValidator.ts
- src/identity/interaction/util/WebIdOwnershipValidator.ts
Require a registration token for Solid OIDC Issuer registration.
Resolves: https://github.com/solid/community-server/issues/581
Note: we'll need to get this through the specification track once we find this stable/working/useful enough in order to get a standard predicate for the confirmation token.
> feat: Require an issuer registration token

- src/storage/accessors/FileDataAccessor.ts
- test/unit/storage/accessors/FileDataAccessor.test.ts
Removes generation of posix:size for filesystem-based containers, if still wanted for issue #445.
> fix: do not output filesystem container size

- config/presets/ldp/response-writer.json
- src/authorization/AllowEverythingAuthorizer.ts
- src/authorization/Authorization.ts
- src/authorization/Authorizer.ts
- src/authorization/AuxiliaryAuthorizer.ts
- src/authorization/WebAclAuthorization.ts
- src/authorization/WebAclAuthorizer.ts
- src/index.ts
- src/ldp/AuthenticatedLdpHandler.ts
- src/ldp/http/metadata/WacAllowMetadataWriter.ts
- src/ldp/operations/GetOperationHandler.ts
- src/ldp/operations/HeadOperationHandler.ts
- src/ldp/operations/Operation.ts
- src/util/Vocabularies.ts
- test/integration/LdpHandlerWithAuth.test.ts
- test/integration/ServerWithAuth.test.ts
- test/unit/authorization/AllowEverythingAuthorizer.test.ts
- test/unit/authorization/WebAclAuthorization.test.ts
- test/unit/authorization/WebAclAuthorizer.test.ts
- test/unit/ldp/AuthenticatedLdpHandler.test.ts
- test/unit/ldp/http/metadata/WacAllowMetadataWriter.test.ts
- test/unit/ldp/operations/GetOperationHandler.test.ts
- test/unit/ldp/operations/HeadOperationHandler.test.ts
Closes #225.
Depends on #554 since there are several changes to permissions and authorization there.
I tried to tread a fine line between not making anything to ACL-specific, but also not adding too many interfaces/classes just for this single header.
The idea is that an `Authorizer` now returns an `Authorization` object (in case it doesn't fail) which is an empty interface except for the `addMetadata` function, allowing full freedom on how to fill that in depending on the authorization model being used. This then gets attached to the `Operation`, and the GET/HEAD handlers call the `addMetadata` on the resulting metadata, which then gets used by a `MetadataWriter` to create the header.
I choose to have the `addMetadata` function in the `Authorization` object since otherwise we would need …
> Support WAC-Allow header

- Dockerfile
The Dockerfile attempts to copy multiple JSON files with the `COPY` command.
However, this is not possible with `.` as directory. This can be fixed by using `./` as directory path.
Fixes #641
Tested on the following setup:
- Armbian 21.02.2 Focal
- Odroid HC2 (armv7)
> fix: Docker COPY command for multiple files

- README.md
This repo has a couple of useful additional configurations for the community-server, I think we should link to it in the readme so it's more discoverable.
> Include solid/community-server-recipes in the readme

- templates/pod/profile/card.acl
Solves #657 by adding ACL file for profile card.
Signed-off-by: Wouter Termont <woutermont@gmail.com>
> fix: make new pod profile card public

- src/ldp/UnsecureWebSocketsProtocol.ts
- src/ldp/http/OriginalUrlExtractor.ts
- src/util/HeaderUtil.ts
- test/unit/ldp/UnsecureWebSocketsProtocol.test.ts
- test/unit/ldp/http/OriginalUrlExtractor.test.ts
- test/unit/util/HeaderUtil.test.ts
This uses the first value from `X-Forwarded-Host` and `X-Forwarded-Proto` if they're present and the standard `Forwarded` header is not.
Please let me know if I can implement this in a different way. I tried to follow existing patterns and limit the changes required.
Resolves #645
> Fallback to X-Forwarded-* headers

- config/presets/identity/email-password-interaction-policy.json
- src/identity/interaction/IdpSessionHttpHandler.ts
- src/index.ts
- test/integration/Identity.test.ts
- test/integration/IdentityTestState.ts
- test/unit/identity/interaction/IdpSessionHttpHandler.test.ts
This was needed to log in again after logging out (context: https://gist.github.com/joachimvh/e430b8e9023f2ac602a92e95c9b5e5d8 )
This is the same way it happened in the old Idp. I do wonder if we should not take different actions based on the prompt reasons because it does feel weird that this just logs the user in again.
Also added relevant integration test.
> Create handler for the confirm page

- config/presets/identity/solid-identity-provider.json
- src/identity/IdentityProviderFactory.ts
- test/unit/identity/IdentityProviderFactory.test.ts
This way we have full control over what gets returned to the user. Currently it used the default error render handler of the oidc library which logged a warning every time (but did have prettier html than printing the error like this I guess 😄 ).
> feat: Use ErrorResponseWriter for handling oidc errors

- config/presets/identity/email-password-interaction-policy.json
- config/presets/identity/solid-identity-provider.json
- src/identity/configuration/KeyGeneratingIdpConfigurationGenerator.ts
- src/identity/interaction/email-password/EmailPasswordInteractionPolicy.ts
- src/identity/interaction/email-password/handler/EmailPasswordForgotPasswordHandler.ts
- test/unit/identity/configuration/KeyGeneratingIdpConfigurationGenerator.test.ts
- test/unit/identity/interaction/email-password/EmailPasswordInteractionPolicy.test.ts
- test/unit/identity/interaction/email-password/handler/EmailPasswordForgotPasswordHandler.test.ts
This way the `idp` part of the URL is no longer hardcoded in the code. It still is in the config but that will be more complex to solve since it's also part of some regexes in there.
As an added bonus `KeyGeneratingIdpConfigurationGenerator` now also works with base URLs that are non-root.
> feat: Make idp parameter dynamic

- src/ldp/http/BasicRequestParser.ts
- src/ldp/http/OriginalUrlExtractor.ts
- src/ldp/representation/RepresentationMetadata.ts
- src/storage/accessors/InMemoryDataAccessor.ts
- src/storage/conversion/ChainedConverter.ts
- src/storage/mapping/BaseFileIdentifierMapper.ts
- src/util/handlers/WaterfallHandler.ts
Noticed there were still some cases were an `Error` could be thrown at runtime. Not really an issue since there's a catch at the end to convert those to 500 but still nicer to be consistent.
> fix: Use HttpErrors instead of Errors

- src/server/HttpRequest.ts
- src/util/StreamUtil.ts
- test/integration/ServerFetch.test.ts
- test/unit/server/HttpRequest.test.ts
- test/unit/util/StreamUtil.test.ts
Closes #646.
This PR is mostly comments and tests and not that much code. The code change is that the `pipeSafely` function now no longer calls the `pump` library to pipe when the source stream is an `HttpRequest`. Reason being that the `pump` library destroys the source stream if the destination stream errors. We want this behaviour, but not for the incoming request since that also closes the outgoing response.
I actually expected this to be a problem when the `pump` library got added to handle piping streams, but everything seemed to work so no change was needed. But apparently this does happen in specific cases so it's probably a timing issue where some errors are handled fast enough by our server and some aren't.
> fix: Prevent HttpRequest from being closed when downstream stream fails

- templates/pod/profile/card.acl
Closes #657 . Actually that one should have already been closed but it still being open made me discover that the second part of the acl file was still that of the container instead of the document.
> fix: Allow owners to edit their own profile

- README.md
- config/presets/cli-params.json
- config/presets/http.json
- config/presets/pod-dynamic.json
- config/presets/pod-management.json
- src/init/CliRunner.ts
- src/pods/generate/TemplatedResourcesGenerator.ts
- src/server/middleware/StaticAssetHandler.ts
- src/util/PathUtil.ts
- test/integration/DynamicPods.test.ts
- test/integration/PodCreation.test.ts
- test/integration/ServerFetch.test.ts
- test/integration/Subdomains.test.ts
- test/integration/WebSocketsProtocol.test.ts
- test/integration/config/server-dynamic-unsafe.json
- test/integration/config/server-subdomains-unsafe.json
- test/integration/config/server-without-auth.json
- test/unit/init/CliRunner.test.ts
- test/unit/pods/generate/TemplatedResourcesGenerator.test.ts
- test/unit/server/middleware/StaticAssetHandler.test.ts
- test/unit/util/PathUtil.test.ts
Closes #650.
I'm still not 100% fan of this solution but I can't think of anything better and it is nice that now it's easier to have paths in configs. Only other option I could think of was passing a boolean along to indicate if a path should be resolved against module root or cwd but that seems worse.
While I was working on the paths I also used this opportunity to remove the `podTemplateFolder` variable. In practice this value is always going to be the same unless an advanced user wants to do something specific.
> Allow file paths to be relative to module root

- src/ldp/representation/RepresentationPreferences.ts
- src/storage/conversion/ConstantConverter.ts
- src/storage/conversion/ContentTypeReplacer.ts
- src/storage/conversion/ConversionUtil.ts
- src/storage/conversion/IfNeededConverter.ts
- src/storage/conversion/QuadToRdfConverter.ts
- src/storage/conversion/TypedRepresentationConverter.ts
- test/integration/GuardedStream.test.ts
- test/unit/storage/conversion/ConversionUtil.test.ts
- test/unit/storage/conversion/TypedRepresentationConverter.test.ts
In the process of doing some changes for #697 I realized the conversion utility functions didn't cover the needs for the new ChainedConverter. I started making some small changes and ended up completely rewriting most of the main functions in there. I mostly tried to bring some more consistency in the function signatures and adapted some functions based on how they were actually used and needed.
This will need another refactor at some point for supporting content type parameters as in #458 but these changes should hopefully be closer to what is needed there. Supporting those also would require changes in the header parsers so I didn't go there yet.
> refactor: Extend and update the ConversionUtil functions

- config/presets/representation-conversion.json
- src/ldp/representation/RepresentationPreferences.ts
- src/storage/conversion/ChainedConverter.ts
- src/storage/conversion/ConstantConverter.ts
- src/storage/conversion/ContentTypeReplacer.ts
- src/storage/conversion/ConversionUtil.ts
- src/storage/conversion/IfNeededConverter.ts
- src/storage/conversion/QuadToRdfConverter.ts
- src/storage/conversion/TypedRepresentationConverter.ts
- test/integration/GuardedStream.test.ts
- test/unit/storage/conversion/ChainedConverter.test.ts
- test/unit/storage/conversion/ConversionUtil.test.ts
- test/unit/storage/conversion/TypedRepresentationConverter.test.ts
Closes #484, see discussion there as well.
Instead of creating a new class I updated `ChainedConverter` since we would have no need for that one anymore after this.
The `canHandle` call of this one is going to be more expensive than most other classes, but this should always be the last handler that gets checked so this should be fine.
There are some parts that could be move to separate files: the cache could be a separate class file, some functions could be moved to `ConversionUtil`, but they are very specific to this implementation so it made sense to me to keep them there.
> feat: Update ChainedConverter to create dynamic paths

- src/ldp/http/AcceptPreferenceParser.ts
- src/storage/conversion/ChainedConverter.ts
- test/integration/ServerFetch.test.ts
- test/unit/ldp/http/AcceptPreferenceParser.test.ts
- test/unit/storage/conversion/ChainedConverter.test.ts
Closes #735.
This was a result of the new ChainedConverter not supporting missing type preferences. Actually it did support those, except that support was right after it first checked if the type preferences were there so it never got that far.
The reason the request didn't get handled by the IfNeedBeConverter is because a container was requested, which always requires conversion (because it returns quads).
I added some related integration tests. None of these tests would have caught this though, since it sets the Accept header as an empty string, which we interpret differently than a missing Accept header (`{ }` vs `undefined`). Unfortunately if you don't set the the Accept header in fetch it defaults it to `*/*`. Perhaps there are ways around this but would have to investigate.
> fix: Support missing type preferences in ChainedConverter

- src/init/RootContainerInitializer.ts
- src/ldp/representation/RepresentationMetadata.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/accessors/DataAccessor.ts
- src/storage/accessors/FileDataAccessor.ts
- src/storage/accessors/InMemoryDataAccessor.ts
- src/storage/accessors/SparqlDataAccessor.ts
- src/util/QuadUtil.ts
- src/util/ResourceUtil.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
- test/unit/storage/accessors/FileDataAccessor.test.ts
- test/unit/storage/accessors/InMemoryDataAccessor.test.ts
- test/unit/storage/accessors/SparqlDataAccessor.test.ts
- test/unit/util/QuadUtil.test.ts
- test/util/Util.ts
Closes #385 (again).
This reduces the performance for SPARQL backends due to the extra calls. This might actually increase the performance in some situations for file/memory backends.
> Prevent metadata of auxiliary resources in container metadata

- .dockerignore
- Dockerfile
I just tried to build the Dockerfile, and noticed 3 problems, which are fixed in this PR.
1. The Dockerfile contained an `npm audit` call, which failed at the time of writing. I removed it in this PR because including it in the Dockerfile feels like a confusion of responsibilities. This is something that should be run earlier in the lifecycle, i.e., during CI.
2. Scripts were ignored during `npm install`, which breaks some dependencies at runtime that require node-gyp, such as `bcrypt`.
3. Since `node_modules` are re-fetched during the build step, they can be excluded from the Docker context, thereby significantly speeding up builds.
> Improvements to Dockerfile

- config/ldp/metadata-writer/writers/constant.json
This PR exposes headers that are required by the [Solid spec](https://solidproject.org/TR/protocol#reading-resources) as to enable client-side libs to know if and how resources can be updated.
This is a temporary solution until #572 and #577 are implemented.
> Expose constant Allow and Accept-Post headers

- src/identity/IdentityProviderHttpHandler.ts
- src/identity/interaction/email-password/EmailPasswordUtil.ts
- src/identity/interaction/email-password/handler/ResetPasswordHandler.ts
- src/identity/interaction/util/IdpRouteController.ts
- src/identity/util/FetchUtil.ts
- src/ldp/AuthenticatedLdpHandler.ts
- src/ldp/http/BasicResponseWriter.ts
- src/ldp/http/SparqlUpdateBodyParser.ts
- src/server/BaseHttpServerFactory.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/accessors/SparqlDataAccessor.ts
- src/storage/conversion/ConversionUtil.ts
- src/util/errors/ErrorUtil.ts
- src/util/errors/HttpError.ts
- src/util/handlers/WaterfallHandler.ts
- test/unit/identity/interaction/email-password/EmailPasswordUtil.test.ts
- test/unit/identity/interaction/email-password/handler/ResetPasswordHandler.test.ts
- test/unit/identity/interaction/util/IdpRouteController.test.ts
- test/unit/identity/util/FetchUtil.test.ts
- test/unit/ldp/http/BasicResponseWriter.test.ts
- test/unit/server/BaseHttpServerFactory.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
- test/unit/storage/conversion/ConversionUtil.test.ts
- test/unit/util/errors/ErrorUtil.test.ts
- test/unit/util/handlers/WaterfallHandler.test.ts
Closes #763.
The main changes are in ErrorUtil, most of the rest is based on those changes.
I also fixed some inconsistenties here and there in how we handled non-native errors. Sometimes they were re-thrown, sometimes a new error object got made instead. This PR should make everything around these a lot more consistent.
> feat: Add better support for non-native errors

- src/storage/keyvalue/JsonResourceStorage.ts
- src/storage/keyvalue/WrappedExpiringStorage.ts
- test/unit/storage/keyvalue/JsonResourceStorage.test.ts
Closes #769.
The problem occurred when the storage container was being accessed if it didn't exist yet.
> fix: Prevent uncaught error in JsonResourceStorage

- src/identity/IdentityProviderFactory.ts
- test/integration/Identity.test.ts
Accidentally stumbled upon this. Due to the oidc library using koa internally there was an issue piping the error output since we switched to the new error writing. The new integration test fails before this change (the error text isn't written).
> fix: Correctly render internal IDP errors

- package-lock.json
- package.json
- src/storage/patch/SparqlUpdatePatchHandler.ts
- test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts
Closes #784 and closes #15 (sort of).
Depends on #781.
The checks are there to make sure we only support BGP queries, but there's not really anything stopping us from allowing everything. At that point we could even remove the algebra body parser since we now only use it for validating.
> fix: Support BGPs with variables in SPARQL UPDATE queries

- src/ldp/auxiliary/LinkMetadataGenerator.ts
- src/ldp/representation/RepresentationMetadata.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/accessors/FileDataAccessor.ts
- src/util/TermUtil.ts
- src/util/Vocabularies.ts
- test/unit/ldp/auxiliary/LinkMetadataGenerator.test.ts
- test/unit/ldp/representation/RepresentationMetadata.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
- test/unit/storage/accessors/FileDataAccessor.test.ts
- test/unit/util/TermUtil.test.ts
Closes #774 .
Alternative solution to #782 .
In #782 the solution is to force all functions that generate metadata to also have a function that removes the same metadata.
The solution in this PR is to assign that metadata to a specific graph and then remove that entire graph from the metadata before storing it in the backend.
This second solution makes many things a lot easier, as it no longer requires double the work when generating metadata. The main issue with this one is that introducing graphs into the metadata might complicate certain things and make it harder to understand how to use it. I tried to keep everything working as it used to in case no graphs are mentioned. In general the idea is that it shouldn't matter in which graph the metadata is stored when requesting information. …
> Remove generated metadata by using metadata graphs

- templates/idp/email-password-interaction/main.css
The current styles don't work properly in small screens (see the screenshots below for an example).
This could be fixed in other ways, for example moving the background to the `body` and fixing the margins in the card. But this is the quickest way I found without changing too much code. I'm also not familiar with the rest of the styles, so if there's anyone who knows more about the codebase and knows a better fix, please go ahead :).
<details>
<summary>Screenshots</summary>
Before:
After:
</details>
> Fix idp styles for small screens

- src/storage/conversion/ErrorToTemplateConverter.ts
- src/util/errors/HttpError.ts
- test/unit/util/errors/HttpError.test.ts
- test/unit/util/identifiers/BaseIdentifierStrategy.test.ts
The fact that `cause` etc. are set through `options` on the constructor should IMHO not influence how they are exposed.
> Assign properties directly to error

- config/storage/resource-store/dynamic.json
- config/storage/resource-store/file.json
- config/storage/resource-store/memory.json
- config/storage/resource-store/regex.json
- config/storage/resource-store/sparql.json
- config/util/index/default.json
- config/util/index/example.json
- config/util/representation-conversion/default.json
- src/index.ts
- src/storage/IndexRepresentationStore.ts
- test/unit/storage/IndexRepresentationstore.test.ts
Closes #800 .
Unfortunately implementing this as a converter is impossible since that would create a circular dependency between the converter and the store.
The main reason I would have preferred a converter can be seen in the config changes. Adding a store to the stack of stores requires more changes. This did make me think that perhaps we should split up the store configs into 2 features since the first part is the same for all stores.
> Add support for index.html resources

- .github/workflows/schedule.yml
- test/deploy/conformance.env
Closes #789 .
I initially based this on the script at https://github.com/solid/conformance-test-harness/blob/main/scripts/css.sh which uses a docker container, but since the action is already contained anyway the script now just installs locally. This saves us a few steps and doesn't require the https setup. I still have the version that uses docker should that be preferred.
Example output at https://github.com/solid/community-server/runs/3068099528 . The relevant step is "Run the test harness". The logger is configured to also output JSON at the end should we want to parse these results. Currently nothing is done with these results yet though.
> test: Add github actions for conformance test harness

- src/storage/IndexRepresentationStore.ts
- test/unit/storage/IndexRepresentationstore.test.ts
> fix: Keep container metadata when returning index.html representation

- src/pods/generate/TemplatedResourcesGenerator.ts
- src/pods/generate/variables/RootFilePathHandler.ts
- src/storage/accessors/FileDataAccessor.ts
- src/storage/mapping/BaseFileIdentifierMapper.ts
- src/storage/mapping/FileIdentifierMapper.ts
- test/unit/pods/generate/TemplatedResourcesGenerator.test.ts
- test/unit/pods/generate/variables/RootFilePathHandler.test.ts
- test/unit/storage/mapping/BaseFileIdentifierMapper.test.ts
- test/unit/storage/mapping/ExtensionBasedMapper.test.ts
- test/unit/storage/mapping/FixedContentTypeMapper.test.ts
- test/unit/storage/mapping/SubdomainExtensionBasedMapper.test.ts
Based on the comment in https://github.com/solid/community-server/pull/825#discussion_r672563981
This turned out bigger than expected so having a separate PR for this.
This completely moves all knowledge of how metadata files are stored to the file mapper, making this the only place the '.meta' is found.
> feat: Move all metadata file knowledge to file mapper

- src/storage/IndexRepresentationStore.ts
- test/integration/LdpHandlerWithoutAuth.test.ts
- test/unit/storage/IndexRepresentationstore.test.ts
- test/util/FetchUtil.ts
Closes https://github.com/solid/community-server/issues/844
@joachimvh Advice on how to fix the integration test?
I could add content type to `getResource`, or just settle for Turtle. But I like the integration tests for HTML.
> Do not serve index on */*

- src/identity/interaction/email-password/handler/RegistrationHandler.ts
- test/unit/identity/interaction/email-password/handler/RegistrationHandler.test.ts
Closes #845.
This does completely remove the option for using different pod templates/template configs that require new variables without creating a new RegistrationHandler. But nobody probably knows that you can change the pod templates or even that we have dynamic pods with template configs 😉
> fix: Clean pod creation input parameters during registration

- config/identity/handler/default.json
- config/identity/handler/key-value/storage.json
- config/storage/key-value/memory.json
- config/storage/key-value/resource-store.json
- config/util/resource-locker/memory.json
- config/util/resource-locker/redis.json
- test/integration/config/server-memory.json
Closes #862 
My proposal for a solution (includes some cleanup for the storage configs).
I would use a specific storage for the lockers that only uses the backend. The expectation is then that the lockers handle the locking themselves (which they currently do).
All other classes can then use a storage that still references the full store stack. The only one we currently have is the IDP one.
I also updated one integration config to use the resource store storage so this would be caught by tests using this config.
After #757 (which is how I discovered this) the plan is to update all the default configs we have to use this kind of storage instead of the memory one which is now the default.
> fix: Prevent cyclical dependency with locker and storage

- config/path-routing.json
- config/sparql-endpoint.json
Closes #840 .
Due to all the work on storage I realized what the problem was and how to easily fix it.
The problem is that the sparql store was using the ResourceStore for the internal storage. But in that case the store only accepts RDF while the internal storage uses JSON. This explains the error message in the issue above since the converter tried to conver the JSON to JSON-LD and was missing the context. This also means #864 completely broke the sparql config since there we made it so the locker also used the ResourceStore for internal storage.
The solution is to just use the memory storage instead since that one does accept everything. It is partially a band-aid solution though since this means all IDP data (e.g. registrations) will be lost on server restart.
A more comprehensive …
> fix: Use memory key/value storage for sparql backends

- config/util/identifiers/subdomain.json
- config/util/identifiers/suffix.json
- src/storage/mapping/ExtensionBasedMapper.ts
- src/storage/mapping/SubdomainExtensionBasedMapper.ts
- src/util/ContentTypes.ts
- templates/config/filesystem.json
- test/unit/storage/mapping/ExtensionBasedMapper.test.ts
A temporary fix until a more generic solution is implemented (#768).
> Fix TriG documents not being PUT-able

- config/storage/middleware/default.json
- config/util/index/default.json
- config/util/index/example.json
- config/util/representation-conversion/converters/errors.json
- src/storage/conversion/ErrorToTemplateConverter.ts
- test/unit/storage/conversion/ErrorToTemplateConverter.test.ts
For `IndexRepresentationStore` I have simply removed the option to disable it. Due to our store stack architecture and the fact that with Components.js you need the classname for parameters there is not really an easy way to replace it with a passthrough store. One other option would be to have an alternative `config/resource-store/middleware` feature that has the stack without the index store. If required I'll add that instead. Note that you can actually disable the index store by setting its `mediaRange` to a useless range.
The second commit is my suggestion on how to handle the templates in the `ErrorToTemplateConverter`. The idea is to set default templates in the class which can then be overwritten if needed. This does roll back a part of the `TemplateEngine` changes since this …
> Further config simplification

- config/identity/ownership/token.json
- package-lock.json
- package.json
- src/identity/ownership/TokenOwnershipValidator.ts
- src/identity/storage/WebIdAdapterFactory.ts
- src/util/FetchUtil.ts
- src/util/Vocabularies.ts
- test/unit/identity/ownership/TokenOwnershipValidator.test.ts
- test/unit/identity/storage/WebIdAdapterFactory.test.ts
- test/unit/util/FetchUtil.test.ts
This way we use our own converters (and we remove a bunch of dependencies).
> feat: Rewrite TokenOwnershipValidator behaviour to remove @rdfjs/fetch dependency

- package-lock.json
- package.json
The 0.11.0 release of https://github.com/solid/access-token-verifier is a serious rewrite improving quality of tests as well as organisation and readability of the project. It shouldn't introduce any breaking changes and all tests are passing, but I'd like to have it in production for a little bit of time before calling it a 1.0. Ideally, the code base would be checked by a second pair of eyes which should be much more doable in its current state than previously.
> chore: Update access token verifier

- config/identity/handler/interaction/routes/session.json
- src/identity/IdentityProviderHttpHandler.ts
- src/identity/interaction/SessionHttpHandler.ts
- src/identity/interaction/email-password/handler/ForgotPasswordHandler.ts
- src/identity/interaction/email-password/handler/InteractionHandler.ts
- src/identity/interaction/email-password/handler/LoginHandler.ts
- src/identity/interaction/email-password/handler/RegistrationHandler.ts
- src/identity/interaction/email-password/handler/ResetPasswordHandler.ts
- test/unit/identity/IdentityProviderHttpHandler.test.ts
- test/unit/identity/interaction/SessionHttpHandler.test.ts
- test/unit/identity/interaction/email-password/handler/ForgotPasswordHandler.test.ts
- test/unit/identity/interaction/email-password/handler/LoginHandler.test.ts
- test/unit/identity/interaction/email-password/handler/RegistrationHandler.test.ts
- test/unit/identity/interaction/email-password/handler/ResetPasswordHandler.test.ts
No longer passes the Response object to the InteractionHandlers. Instead passes an optional Interaction object that will be defined if the OIDC library is waiting on us to finish up an interaction (specifically: we're trying to log a user in).
@RubenVerborgh That Interaction object can be used in the RegistrationHandler to solve #880 in case you want to that fixed before 1.0.0. Just need to check if it is defined or not.
> feat: Pass optional Interaction to InteractionHandlers

- config/util/representation-conversion/converters/errors.json
- config/util/representation-conversion/converters/markdown.json
Noticed some imports in configs that shouldn't be there.
Technically this is breaking if someone is importing those specifically and depends on those imports 😅 . If that is an issue this should be merged in a different branch.
> chore: Clean up unnecessary imports

- src/identity/IdentityProviderHttpHandler.ts
- templates/error/descriptions/E0002.md.hbs
- test/unit/identity/IdentityProviderHttpHandler.test.ts
Closes #880 
Now that the IDP handles content-negotiation for errors the login error can have a more detailed explanation.
> fix: Explain why logging in will not work

- .github/workflows/schedule.yml
Was required due to update to the conformance test suite.
Test is going to fail since we don't return a 201 yet when creating a new resource.
> fix: Update conformance script to target full URI

- config/ldp/authorization/authorizers/acl.json
- src/authorization/WebAclAuthorizer.ts
Changing the name of the parameter to indicate that this store only has to contain the ACL resources.
(This might become relevant later if it turns out we also need to access resource state to make ACL decisions, as in https://github.com/solid/web-access-control-spec/issues/97)
> Rename resourceStore to aclStore

- package.json
Currently all instance configurations in `config/` uses `scs`, `files-scs` prefixes in compact-iris. The prefix seems expected to get defined in json-ld context that gets generated on `build:components`.
But it is unclear why prefix is getting generated to magical `scs` on build. after verifying with `components-generator`, it seems using a function https://github.com/LinkedSoftwareDependencies/Components-Generator.js/blob/5b7a93b42f773d9cd83a7f62a5de7d03a59bfe66/lib/serialize/ContextConstructor.ts#L23 to heuristically generate fallback prefix from package-name.
It's good to be deterministic and not to depend on heuristics-sans-contract, as other code assuming this prefix. Also newbies can understand from where those assumptions came from.
> Make json-ld context prefix generation deterministic

- config/storage/key-value/resource-store.json
- config/util/auxiliary/strategies/acl.json
- src/ldp/auxiliary/AuxiliaryStrategy.ts
- src/ldp/auxiliary/ComposedAuxiliaryStrategy.ts
- src/ldp/auxiliary/RoutingAuxiliaryStrategy.ts
- src/storage/DataAccessorBasedStore.ts
- test/integration/LdpHandlerWithoutAuth.test.ts
- test/unit/ldp/auxiliary/ComposedAuxiliaryStrategy.test.ts
- test/unit/ldp/auxiliary/RoutingAuxiliaryStrategy.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
Closes #892 
I did not create an auxiliary strategy that identifies all resources starting with an `.` as auxiliary. Some reasons:
The strategy requires there to be an associated resource for an auxiliary resource. The most logical choice would be the container they are located in. The issue is that locking happens on the associated resource, so all access to any of those resources (in the same container) would require the same lock. Might not be horrible but perhaps also not great. On the other hand it is also not possible to construct an auxiliary identifier when taking an associated identifier as input. This is used when deleting a resource to first delete its auxiliary resources.
The locking issue is perhaps not that bad though, and the other parts might indicate an issue with the …
> fix: Hide internal data by making it auxiliary

- RELEASE_NOTES.md
- config/identity/handler/provider-factory/identity.json
- test/integration/Identity.test.ts
Closes #1038.
I don't think this breaks anything for older versions but there might be a case I'm not aware of.
> fix: Add webid claim to webid scope

- .eslintrc.js
- src/http/output/error/ConvertingErrorHandler.ts
- src/http/output/error/SafeErrorHandler.ts
- src/index.ts
- src/util/PromiseUtil.ts
- src/util/errors/ErrorUtil.ts
- src/util/errors/HttpErrorUtil.ts
- src/util/handlers/HandlerUtil.ts
- src/util/handlers/ParallelHandler.ts
- src/util/handlers/UnionHandler.ts
- test/integration/Setup.test.ts
- test/unit/authentication/UnionCredentialsExtractor.test.ts
- test/unit/util/errors/ErrorUtil.test.ts
- test/unit/util/errors/HttpErrorUtil.test.ts
- test/unit/util/handlers/HandlerUtil.test.ts
- test/unit/util/handlers/UnionHandler.test.ts
I opted to interpret the lack of `requireAll` as a sign that handler failures are fine.
Fixes https://github.com/solid/community-server/issues/1031
> Make UnionHandler tolerate handler failures

- RELEASE_NOTES.md
- config/http/handler/default.json
- config/http/handler/handlers/oidc.json
- config/identity/handler/default.json
- config/identity/handler/provider-factory/identity.json
- src/identity/IdentityProviderHttpHandler.ts
- src/identity/OidcHttpHandler.ts
- src/identity/configuration/IdentityProviderFactory.ts
- src/index.ts
- src/server/AuthorizingHttpHandler.ts
- src/server/OperationHttpHandler.ts
- test/integration/Identity.test.ts
- test/integration/config/server-without-auth.json
- test/unit/identity/IdentityProviderHttpHandler.test.ts
- test/unit/identity/OidcHttpHandler.test.ts
- test/unit/identity/configuration/IdentityProviderFactory.test.ts
Makes it so all requests targeting the OIDC library use `/.oidc/*` paths. Now the `IdentityProviderHttpHandler` doesn't have to take that situation into account anymore. Does not remove that much checks, but does make the flow cleaner and removes some implicit assumptions, which might help when updating this class in the future.
This doesn't actually change anything about the server behaviour since those paths should not be hardcoded anywhere, but still targeting the 3.0.0 branch since it is mostly irrelevant for existing installations and will mostly be relevant when adding new 3.0.0 features.
> feat: Move OIDC library behaviour to separate path

- README.md
https://github.com/solid/community-server/issues/1098
Fixes a broken link to developer notes on this page: https://solid.github.io/community-server/docs/#%F0%9F%91%A9%F0%9F%8F%BD%F0%9F%92%BB-developing-server-code
Uses a full URL so that this link works from the hosted docs.
> patch: fix broken link to developer-notes.md from docs index

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
* #1111 
* #1053 
* #728 
This PR adds a docker job to the ci.yml workflow. 
It should only trigger if the following jobs have been executed:
```yaml
needs:
- lint
- test-unit
- test-integration
- test-integration-windows
- validate-components
```
and if the `ref` starts with `refs/tags/v`. 
For now, this should enable building and pushing of tagged versions following semver style.
**Example:**
Github tag: `v1.2.3`  
Docker tags:
* 1
* 1.2
* 1.2.3
* latest (overwrites previous latest tag)
_The necessary secrets should have been added by @RubenVerborgh._
**This temporarily adds some manual versions to immediatly build and push the current image**
- semver.minor: …
> Build and push official docker image

- config/ldp/handler/components/operation-handler.json
- config/ldp/modes/default.json
- config/storage/middleware/stores/patching.json
- src/authorization/permissions/ModesExtractor.ts
- src/authorization/permissions/SparqlUpdateModesExtractor.ts
- src/index.ts
- src/util/handlers/MethodFilterHandler.ts
- src/util/handlers/StaticThrowHandler.ts
- test/integration/LdpHandlerWithoutAuth.test.ts
- test/unit/authorization/permissions/SparqlUpdateModesExtractor.test.ts
- test/unit/util/handlers/MethodFilterHandler.test.ts
- test/unit/util/handlers/StaticThrowHandler.test.ts
Closes #364 
`StaticThrowHandler` is an implementation of the class discussed in the related issue. This PR resolves the cases of returning a 405 in case of unsupported HTTP methods and returning a 415 in case of unsupported PATCH formats. There are probably other situations that also should be updated now, but those can have their own issue when they pop up.
Major change since a class is renamed (would otherwise be a minor).
Extracting access modes for a PATCH request is now split over 2 classes, one which checks the method and one which checks the body. This allows us to differentiate between 405 and 415. This will probably also be useful once #1060 is added.
The 405 fallback is added both when extracting modes and when calling an operation handler. The 415 fallback is added in modes …
> feat: Return correct status codes for invalid requests

- RELEASE_NOTES.md
- config/ldp/handler/components/request-parser.json
- config/ldp/metadata-writer/writers/constant.json
- config/ldp/modes/default.json
- config/storage/middleware/stores/patching.json
- package-lock.json
- package.json
- src/authorization/permissions/N3PatchModesExtractor.ts
- src/http/input/body/N3PatchBodyParser.ts
- src/http/representation/N3Patch.ts
- src/index.ts
- src/storage/patch/N3Patcher.ts
- src/storage/patch/SparqlUpdatePatcher.ts
- src/util/ContentTypes.ts
- src/util/QuadUtil.ts
- src/util/Vocabularies.ts
- src/util/errors/UnprocessableEntityHttpError.ts
- src/util/handlers/MethodFilterHandler.ts
- test/.eslintrc.js
- test/integration/N3Patch.test.ts
- test/unit/authorization/permissions/N3PatchModesExtractor.test.ts
- test/unit/http/input/body/N3PatchBodyParser.test.ts
- test/unit/storage/patch/N3Patcher.test.ts
- test/unit/util/QuadUtil.test.ts
- test/unit/util/errors/HttpError.test.ts
- test/unit/util/handlers/MethodFilterHandler.test.ts
- test/util/FetchUtil.ts
- test/util/Util.ts
Closes #1060 
Depends on #1119 due to changes in the PATCH configuration there.
Fully adds support for N3 patch as described in the [spec](https://solid.github.io/specification/protocol#n3-patch).
Integration tests are based on those in NSS, making N3 Patch probably the most comprehensively tested part of the codebase.
> feat: Add support for N3 Patch

- .github/workflows/ci.yml
#1140 
This PR will add 2 new docker tags to the [official docker image](https://hub.docker.com/r/solidproject/community-server/tags) by updating the CI.
---
**branch:** `main`  
**docker tag:** `:edge`
This tag would be generated on each commit push on the `main` branch. The idea is that you can have a docker image of the latest developments. I suggest `:edge` in favor of the earlier proposed `:dev` tagname, because it better self-explains what it is. It is on the edge of the main repository. If you need that for development, you'll pick it.  
If we were to use the `:dev` tag, you first have to at least find out what that really means.
---
**branch:** `versions/*`  
**docker tag:** `:next`
This tag would be generated on each commit push on the `versions/*` branch. There should only be …
> feat: Generate `:next` and `:edge` docker tags

- config/identity/handler/account-store/default.json
- config/storage/key-value/memory.json
- config/storage/key-value/resource-store.json
- src/identity/interaction/email-password/storage/BaseAccountStore.ts
- test/unit/identity/interaction/email-password/storage/BaseAccountStore.test.ts
#744 
This PR will split the AccountStorage being used, into an AccountStorage (which still has the KeyValueStorage type) and a new ForgotPasswordStorage (of type ExpiringStorage).
The purpose of this change is to allow for ForgotPassword entries to be purged from the storage (be it in-memory or file based) when users don't click the link sent in the email. A default expiration of 15 minutes is added.
> Split AccountStorage and ForgotPasswordStorage (expiring now)

- src/http/input/metadata/ContentTypeParser.ts
- src/http/representation/RepresentationMetadata.ts
- src/util/FetchUtil.ts
- src/util/HeaderUtil.ts
- src/util/Vocabularies.ts
- test/unit/http/input/body/SparqlUpdateBodyParser.test.ts
- test/unit/http/input/metadata/ContentTypeParser.test.ts
- test/unit/http/representation/RepresentationMetadata.test.ts
- test/unit/util/HeaderUtil.test.ts
#458 
**Initial plan, but will not implement now**
Replacing the [`RepresentationMetadata#contentType`](https://github.com/solid/community-server/blob/3b353affb1f0919fdcb66172364234eb59c2e3f6/src/http/representation/RepresentationMetadata.ts#L312-L318) currently in use (as a string) with an object that also contains the parsed parameters would lead to a lot of changes in the codebase (and in testing). The main issue being that the RepresentationMetadata class would no longer consist of only single `<identifier> <predicate> <object>` triples to store metadata. The new `contentType` would need something along the lines of this structure:
```turtle
<> ma:format _:format.
_:format     solid-type:value     "application/json";
solid-type:parameter _:parameter1.
_:parameter1 rdfs:label …
```
> Feat: Store content type parameters

- RELEASE_NOTES.md
- config/identity/handler/account-store/default.json
- config/identity/handler/adapter-factory/webid.json
- config/identity/handler/provider-factory/identity.json
- config/identity/ownership/token.json
- config/storage/key-value/memory.json
- config/storage/key-value/resource-store.json
- config/storage/key-value/storages/storages.json
- src/index.ts
- src/storage/keyvalue/EncodingPathStorage.ts
- src/storage/keyvalue/JsonResourceStorage.ts
- test/unit/storage/keyvalue/EncodingPathStorage.test.ts
- test/unit/storage/keyvalue/JsonResourceStorage.test.ts
Inspired by the fact that some new storages will be needed for #972
Creating new key/value storages was always a bit of a hassle as they had to be duplicated in 2 config files. The new solution makes it so you can create a storage in a specific container while still referencing the base storage. This way they only have to be defined once and can be moved to the config where they are needed, as many storages are only used by 1 class. This also makes it easier in the future to quickly create new storages.
A practical advantages of having many different storages is that this makes it easier to find which internal files need to be changed/removed in case of data migration or other related issues.
This PR doesn't change anything to the internal data structure (unless I made a typo somewhere) …
> Simplify key/value storage configuration

- src/index.ts
- src/storage/keyvalue/EncodingPathStorage.ts
- src/storage/keyvalue/JsonResourceStorage.ts
- src/storage/keyvalue/WrappedExpiringStorage.ts
- src/util/PathUtil.ts
- src/util/TimerUtil.ts
- test/integration/ExpiringDataCleanup.test.ts
- test/integration/LockingResourceStore.test.ts
- test/integration/RedisResourceLockerIntegration.test.ts
- test/unit/init/AppRunner.test.ts
- test/unit/storage/LockingResourceStore.test.ts
- test/unit/storage/keyvalue/EncodingPathStorage.test.ts
- test/unit/storage/keyvalue/JsonResourceStorage.test.ts
- test/unit/util/PathUtil.test.ts
- test/unit/util/StreamUtil.test.ts
- test/unit/util/TimerUtil.test.ts
- test/unit/util/locking/GreedyReadWriteLocker.test.ts
- test/util/Util.ts
Closes #1247
Since all storages use the same source storage in the end this is a bit inefficient now since it will iterate multiple times through all its entries, but this happens only once per hour so should be fine. We could always optimize in the future by adding a `path` parameter to the `entries` function if needed.
Also comes with a new utility test function to resolve pending promises.
> Prevent cleanup of expiring data from crashing the server

- src/storage/accessors/AtomicFileDataAccessor.ts
- src/storage/accessors/FileDataAccessor.ts
- src/storage/keyvalue/JsonFileStorage.ts
- test/unit/pods/generate/TemplatedResourcesGenerator.test.ts
- test/unit/quota/PodQuotaStrategy.test.ts
- test/unit/quota/QuotaStrategy.test.ts
- test/unit/storage/accessors/AtomicFileDataAccessor.test.ts
- test/unit/storage/accessors/FileDataAccessor.test.ts
- test/unit/storage/keyvalue/JsonFileStorage.test.ts
- test/unit/storage/size-reporter/FileSizeReporter.test.ts
- test/unit/util/templates/TemplateEngine.test.ts
- test/util/Util.ts
#1175 
This PR is a WIP
As suggested in the relevant issue, this PR aims to use `fs-extra` instead of `fs` in order to simplify the code for file access.
`fs-extra`. By itself it is already a drop-in replacement for `fs` as all functions of it are attached.
Classes that could be targeted:
- src/storage/accessors/FileDataAccessor.ts
- src/storage/mapping/BaseFileIdentifierMapper.ts
- src/storage/mapping/ExtensionBasedMapper.ts
Is it desireable to change all imports of `fs` to `fs-extra` as it is a full replacement?
> Refactor: use fs-extra instead of fs to simplify file access

- src/authentication/BearerWebIdExtractor.ts
- src/authentication/DPoPWebIdExtractor.ts
- src/authentication/UnsecureWebIdExtractor.ts
- src/http/UnsecureWebSocketsProtocol.ts
- src/http/input/conditions/BasicConditionsParser.ts
- src/identity/interaction/email-password/util/RegistrationManager.ts
- src/identity/storage/WebIdAdapterFactory.ts
- src/index.ts
- src/pods/generate/SubdomainIdentifierGenerator.ts
- src/pods/generate/SuffixIdentifierGenerator.ts
- src/server/middleware/WebSocketAdvertiser.ts
- src/storage/IndexRepresentationStore.ts
- src/storage/conversion/ErrorToTemplateConverter.ts
- src/util/HeaderUtil.ts
- src/util/StringUtil.ts
- test/integration/Middleware.test.ts
- test/unit/util/HeaderUtil.test.ts
- test/unit/util/StringUtil.test.ts
#807 
The goal of these changes is to reduce the number of (repeated) regex occurrences in the codebase, by wrapping these into helper functions to promote reuse and increase readability.
A new set of helper function is introduced in `StringUtil.ts`: `splitCommaSeparated`, `sanitizeUrlPart` and `isValidFileName`.
`HeaderUtil.ts` has been extended with helper functions `matchesAuthorizationScheme` and `hasScheme`. As both these functions make use of dynamic regexes, a simple cache mechanism using two `Map` instances was implemented.
- semver.major: Breaking changes. This includes changing interfaces or …
> feat: new helper functions to replace regexes #807

- src/http/auxiliary/LinkMetadataGenerator.ts
- src/http/input/metadata/SlugParser.ts
- src/http/output/metadata/LinkRelMetadataWriter.ts
- src/http/output/metadata/MappedMetadataWriter.ts
- src/http/representation/RepresentationMetadata.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/accessors/FileDataAccessor.ts
- src/storage/accessors/SparqlDataAccessor.ts
- src/storage/quota/PodQuotaStrategy.ts
- src/util/TermUtil.ts
- test/integration/LockingResourceStore.test.ts
- test/unit/http/auxiliary/LinkMetadataGenerator.test.ts
- test/unit/http/input/metadata/LinkParser.test.ts
- test/unit/http/input/metadata/SlugParser.test.ts
- test/unit/http/ldp/PatchOperationHandler.test.ts
- test/unit/http/ldp/PostOperationHandler.test.ts
- test/unit/http/ldp/PutOperationHandler.test.ts
- test/unit/http/representation/RepresentationMetadata.test.ts
- test/unit/pods/generate/TemplatedResourcesGenerator.test.ts
- test/unit/quota/PodQuotaStrategy.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
- test/unit/storage/accessors/FileDataAccessor.test.ts
- test/unit/storage/accessors/InMemoryDataAccessor.test.ts
- test/unit/storage/conversion/ConstantConverter.test.ts
- test/unit/storage/conversion/ContentTypeReplacer.test.ts
- test/unit/util/TermUtil.test.ts
#466 
- Move `toCachedNamedNode` into `RepresentationMetadata` and make it private
- Only allow `NamedNode` as type of predicates used for metadata
> Only NamedNodes as predicates for metadata

- RELEASE_NOTES.md
- config/app/variables/resolver/resolver.json
- config/https-file-cli.json
- src/init/cli/YargsCliExtractor.ts
- src/init/variables/CombinedSettingsResolver.ts
- test/unit/init/cli/YargsCliExtractor.test.ts
- test/unit/init/variables/CombinedSettingsResolver.test.ts
Was inspired by the comment in https://github.com/CommunitySolidServer/CommunitySolidServer/issues/354#issuecomment-1098096878 to add this feature as it is mostly a quick fix. Also includes a rename from `computers` to `resolvers` that should have been done in the original PR.
This adds a new config that allows setting up an HTTPS server using CLI parameters, that are defined in the config itself. This is now possible due to the CLI configs that we have (and a small change that was required in the yargs parser).
This resolves the issue of people that wanted to use CLI parameters for starting an HTTPS server, and it also provides an example of how to add to the CLI in your own configuration. The advantage is that we don't have to flood our default configurations with CLI options for all …
> feat: Allow dynamically adding CLI parameters in configs

- .github/workflows/ci.yml
- README.md
- package-lock.json
- package.json
- test/integration/Quota.test.ts
- test/util/Util.ts
https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1271#issuecomment-1104962095
Drops support for Node 12 in v5 since Comunica doesn't support it any more.
`rmdir` was deprecated and removed in Node 18.
> chore: Drop support for Node 12

- src/util/PathUtil.ts
- test/integration/FileBackendEncodedSlashHandling.test.ts
- test/integration/config/server-file.json
- test/unit/util/PathUtil.test.ts
- test/util/Util.ts
#1184 
Modified `encodeUriPathComponents` and `decodeUriPathComponents` in `PathUtil.ts` so that url encoded path separator characters (`/`, `\`) no longer erroneously impact the file path that is targeted when using a file backend. The implementation uses two new helper functions `escapeCodecExceptionsForEncoding` and `escapeCodecExceptionsForDecoding` that prepare a path part for encoding and decoding respectively, by replacing all instances of the matching encoded file separator characters with a character or character sequence that results in the follow-up encode/decode to have no effect. The code can be extended with additional path separator characters (or other exceptional characters) to ignore during encoding/decoding, by adding the respective characters to the `codecExceptions` …
> fix: %2F not handled correctly in file backend #1184

- src/storage/accessors/FileDataAccessor.ts
- src/storage/mapping/BaseFileIdentifierMapper.ts
- src/storage/mapping/ExtensionBasedMapper.ts
- test/integration/FileBackend.test.ts
- test/unit/storage/mapping/ExtensionBasedMapper.test.ts
- test/util/Util.ts
#768 
The goal of these changes is to add support for unknown media types when using a file-based backend:
- `mapUrlToDocumentPath` in `ExtensionBasedMapper.ts` no longer throws a NotImplementedHttpError when encountering an unknown media type, but instead falls back to `application/octet-stream` (and .bin extension)
- `writeMetadata` in `FileDataAccessor.ts` retains a metadata entry with the content-type of the request when writing a document that uses an unknown media type (can be detected when the metadata content-type differs from the `ResourceLink` instance that was generated using `mapUrlToDocumentPath`), resulting in this information being written to the metadata file.
- `getFileMetadata` in `FileDataAccessor.ts` uses the content-type stored in the metadata file, if such an entry …
> feat: file-based backend fallback for unknown media types

- commitlint.config.js
- package-lock.json
- package.json
#145 
Git committing will now lint the commit message to adhere to conventional commit format
- Add [`commitlint/cli`](https://www.npmjs.com/package/@commitlint/cli) and [`commitlint/conventional-config` ](https://www.npmjs.com/package/@commitlint/config-conventional)as dev dependency 
- Add a `commit-msg` hook to husky to lint commits
> Add commit linting 

- RELEASE_NOTES.md
- config/ldp/metadata-parser/default.json
- config/storage/backend/global-quota-file.json
- config/storage/backend/pod-quota-file.json
- config/storage/backend/quota/quota-file.json
- src/index.ts
- src/storage/accessors/FilterMetadataDataAccessor.ts
- src/util/QuadUtil.ts
- src/util/Vocabularies.ts
- test/integration/Quota.test.ts
- test/unit/storage/accessors/FilterMetadataDataAccessor.test.ts
#1217 
Removed `ContentLengthParser` from the default MetadataParser configuration. As a result, no unnecessary metadata properties will be retained when writing metadata in `FileDataAccessor`, meaning no .meta files will be generated for scenarios where this is not needed.
Content-length in metadata is only used when validating global or pod based quotas. For configurations that use quota validation, the `ContentLengthParser` is added as an additional handler to the default MetadataParser. I've updated `QuotaValidator` to remove content-length from metadata, once it used this information to estimate the resource size.
- semver.minor: Backwards compatible feature …
> fix: Stop creating meta files for each new resource #1217

- .github/dependabot.yml
- documentation/release.md
- renovate.json
#731 
This PR further builds out our Dependabot setup so Renovate can be retired and we have all version management in one place.
**Notable changes:**
Security updates are checked against the default branch for all packages (npm, docker and github actions). Version updates for docker and github actions are performed against the default branch as well.
Version updates for npm are checked against the versions branch, configured through `target-branch: "versions/5.0.0"` option, this will have to be updated on release (along with the workflow files). These version updates are limited to major versions, patch and minor updates will have no effect (unless when triggered by security updates)
All checks are done nightly, 00:00 Europe/Brussels, so we have fresh PRs with our morning coffee ☕
Husky …
> Chore: replacing Renovate with Dependabot

- src/identity/storage/WebIdAdapterFactory.ts
- test/unit/identity/storage/WebIdAdapterFactory.test.ts
Fixes an issue where client WebIDs were rejected if the `@context` was an array instead of a string.
> fix: Accept client WebIDs with a context array

- package-lock.json
- package.json
- src/http/representation/RepresentationPreferences.ts
- src/storage/routing/ConvertingRouterRule.ts
- src/storage/routing/PreferenceSupport.ts
- test/unit/storage/routing/ConvertingRouterRule.test.ts
- test/unit/storage/routing/PreferenceSupport.test.ts
#298 
Reverting the commits mentioned in #298 . This is to pave the way for tackling #302 and eventually #947.
All the required fixes in components.js and the generator seem to be in place for this.
> Fix: Revert to having ConvertingRouterRule support any number of stores

- src/identity/OidcHttpHandler.ts
- templates/root/prefilled/index.html
- test/unit/identity/OidcHttpHandler.test.ts
#1110
When a root path is used in the base URL, requests to the OIDC provider get rewritten:
`/path/.well-known/openid-configuration` becomes `/.well-known/openid-configuration` before getting passed to the Provider.
Also some links in the setup html page now honor that subpath (`./idp/register` and `./` in the header)
> Fix: Rewrite request with a root path to OIDC Provider

- RELEASE_NOTES.md
- config/sparql-file-storage.json
- config/storage/backend/regex.json
- src/storage/routing/RegexRouterRule.ts
- test/unit/storage/routing/RegexRouterRule.test.ts
#302 
#947 
This PR changes the Regex to ResourceStore mapping from a Map datastructure to an Array datastructure. The idea is that regexes are now tested in a fallthrough order.
This allows for more predictable routing and even allows for a catchall `/.*/` regex at the end as suggested in #947. This change will however not introduce any catching/default behaviour, it will only setup the datastructure to allow this in the future. Any such change would be better introduced as a fix for #947 itself.
~~The first two comments, called `fix: Revert: ...`, are from the parent `fix/#298` branch, once merged, these will be removed after a rebase. So only the latest commit should be reviewed here.~~
- semver.patch: …
> Feat: Have RegexRouterRule take ordered array

- src/logging/LazyLoggerFactory.ts
- src/logging/Logger.ts
- test/unit/logging/LazyLoggerFactory.test.ts
#1325 
Fixes the bug where LazyLoggers are not properly sending the metadata object along, resulting in `{W-???}` in the logs.
> fix: logging component logs as coming from a worker

- RELEASE_NOTES.md
- config/app/init/initializers/prefilled-root.json
- config/app/init/initializers/root.json
- config/app/setup/handlers/setup.json
- config/http/static/default.json
- config/identity/access/initializers/idp.json
- config/identity/access/initializers/well-known.json
- config/identity/handler/interaction/routes/forgot-password.json
- config/identity/handler/interaction/views/html.json
- config/identity/pod/pod-generators/templated.json
- config/identity/pod/resource-generators/templated.json
- config/util/representation-conversion/converters/dynamic-json-template.json
- config/util/representation-conversion/converters/errors.json
- config/util/representation-conversion/converters/markdown.json
- config/util/representation-conversion/default.json
- src/pods/generate/TemplatedPodGenerator.ts
- src/server/middleware/StaticAssetHandler.ts
- src/util/PathUtil.ts
- src/util/templates/EjsTemplateEngine.ts
- src/util/templates/HandlebarsTemplateEngine.ts
- templates/config/defaults.json
- templates/main.html.ejs
- test/unit/pods/generate/TemplatedPodGenerator.test.ts
- test/unit/pods/generate/TemplatedResourcesGenerator.test.ts
- test/unit/server/middleware/StaticAssetHandler.test.ts
- test/unit/util/templates/EjsTemplateEngine.test.ts
- test/unit/util/templates/HandlebarsTemplateEngine.test.ts
#1110 
- Added baseUrl as constructor parameter to the `EjsTemplateEngine` (+ changed configs to pass that variable)
- Engine will now extract path from the baseUrl and pass this as `rootPath` variable to templates
- Templates use the `rootPath` variable instead of `/` root
- `StaticAssetHandler` is also passed baseUrl variable, the url paths passed to it from config are then also prepended with the `rootPath` extracted from baseUrl (root `/` replace with `rootPath`)
Perhaps there is a better way of passing this `baseUrl` or better yet `rootPath` variable directly or is this fine?
**Failing integration test**
Right now  the `integration/DynamicPodTests` are failing... probably because of the config changes, though I can't seem to pinpoint the exact problem.
For example, output of one …
> Feat: Respect root path for static assets and HTML links

- package-lock.json
- package.json
- test/integration/RedisLocker.test.ts
- test/integration/config/server-redis-lock.json
#1182 
Fixes default CLI values being converted to strings, by updating the Components.js dependency to version 5.2.0 (which includes [PR 95](https://github.com/LinkedSoftwareDependencies/Components.js/pull/95)).
> chore(deps): bump componentsjs from 5.1.0 to 5.20

- src/init/cluster/ClusterManager.ts
- test/unit/init/cluster/ClusterManager.test.ts
Now that [PR1333](https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1333) has been merged and thus #1182 has been fixed, the signature of ClusterManager's constructor no longer needs to account for `workers` of type `string`.
> fix: remove workaround for cli parameters being turned into string

- src/http/UnsecureWebSocketsProtocol.ts
- test/unit/http/UnsecureWebSocketsProtocol.test.ts
When debugging with @timbl, we noticed that I had used the wrong property name.
This one is correct: https://nodejs.org/api/tls.html#tlssocketencrypted
Tested on a live instance and adjusted unit tests.
> Use encrypted field to check for TLS

- .github/workflows/ci.yml
*  #643
This PR adds an intermediate stage to the CI pipelines. Instead of build-and-push behaviour, it will now follow build-test-push behaviour.
This happens by first loading the generated images in the local docker repository, then trying to successfully start one of those built images (`latest` and `edge` for the main branch, `next` for the versions branch)
If that doesn't return an error, it can continue by pushing the images to the Docker Hub.
See also here: https://github.com/docker/build-push-action/blob/master/docs/advanced/test-before-push.md
> feat: add test phase for docker images

- src/storage/conversion/RdfToQuadConverter.ts
- test/unit/storage/conversion/RdfToQuadConverter.test.ts
* #1242 
This PR fixes the outstanding issue #1242. This filters out the `application/json` as an input type of the RdfToQuadConverter as suggested. The given reproducer works now and outputs this:
```bash
npm start
echo '{}' | curl -T - -H "Content-Type: application/json" http://localhost:3000/test
curl -H "Accept: text/turtle" http://localhost:3000/test
```
```rdf
<b0> <http://purl.org/dc/terms/title> "NotImplementedHttpError";
<http://purl.org/dc/terms/description> "No conversion path could be made from application/json to text/turtle:1,internal/*:0.";       
<urn:npm:solid:community-server:error:stack> "NotImplementedHttpError: No conversion path could be made from application/json to text/turtle:1,internal/*:0.\n    at ChainedConverter.generatePath …
```
> fix: rdf convertors should not read or write plain JSON

- README.md
- RELEASE_NOTES.md
Just to update the links of README and RELEASE_NOTES to the new documentation site.
> docs: update docs links to new documentation site

- config/ldp/metadata-writer/default.json
- config/ldp/metadata-writer/writers/content-type.json
- config/ldp/metadata-writer/writers/mapped.json
- src/http/input/metadata/ContentTypeParser.ts
- src/http/output/metadata/ContentTypeMetadataWriter.ts
- src/http/representation/RepresentationMetadata.ts
- src/index.ts
- src/util/HeaderUtil.ts
- test/integration/ContentNegotiation.test.ts
- test/unit/http/output/metadata/ContentTypeMetadataWriter.test.ts
- test/unit/http/representation/RepresentationMetadata.test.ts
- test/unit/util/HeaderUtil.test.ts
* Closes #459 
This PR makes sure the ContentType header string now contains the stored parameters too, if there are any.
It is implemented by turning ContentType from an interface into a class and add a `toHeaderValueString()` method.
A new `ContentTypeMetadataWriter` class was also added: this just calls the `toHeaderValueString()` method on the `metadata.contentTypeObject` and adds it as a `Content-Type` header.
All relevant tests were updated and new ones added for 100% coverage.
I suspect this can just target the main, if not, I will rebase it on versions/5.0.0
- semver.major: Breaking changes. This …
> fix: return contenttype header value string with parameters

- documentation/markdown/resource-store.md
- src/http/ldp/PostOperationHandler.ts
- src/http/representation/ResourceIdentifier.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/MonitoringStore.ts
- src/storage/ResourceStore.ts
- src/util/IterableUtil.ts
- test/unit/http/ldp/PostOperationHandler.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
- test/unit/storage/MonitoringStore.test.ts
- test/unit/util/IterableUtil.test.ts
As mentioned in https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1350#pullrequestreview-1027218923
Updates the response type of a `ResourceStore` to use a `HashMap` instead of an object with string keys. Also fixed some issues about how terms were being used.
> Use IdentifierMap for ResourceStore responses

- .github/workflows/ci.yml
* Closes #1382 (again)
Small PR to change the ARM 64bit docker image build to a ARM/v7 (32 bit) image, as this is what was actually needed to run it on a raspberry pi.
> Feat: build docker image for ARM/v7 32bit instead of ARM64

- package-lock.json
- package.json
- src/storage/conversion/RdfToQuadConverter.ts
- test/integration/LdpHandlerWithoutAuth.test.ts
- test/unit/storage/conversion/RdfToQuadConverter.test.ts
* Closes #126
* Relevant for #1366
After adding a feature to rdf-parse.js via this PR https://github.com/rubensworks/rdf-parse.js/pull/42, we are now able to listen to events for `prefix` and `context` when parsing the stream. (it was merged in rdf-parse@2.1.0, so I've updated this dependency)
This should fix the PATCH problem in #126, when updating your turtle file looses the prefix notation.
Note that this works only for those cases where the data stream has been completely read before accessing the metadata.
Eg. the PATCH operation, which is the main case why we store the prefixes in metadata here if there are any.
If we want to make back to back calling of `RdfToQuadConverter.convert` followed by `QuadToRdfConverter.convert` idempotent, then we loose the benefit of streaming (since …
> Feat: Store turtle prefixes in metadata when parsing

- .componentsignore
- RELEASE_NOTES.md
- config/app/variables/default.json
- config/app/variables/resolver/resolver.json
- config/https-file-cli.json
- src/index.ts
- src/init/AppRunner.ts
- src/init/CliResolver.ts
- src/init/cli/CliExtractor.ts
- src/init/variables/CombinedShorthandResolver.ts
- src/init/variables/ShorthandResolver.ts
- src/init/variables/Types.ts
- src/init/variables/extractors/AssetPathExtractor.ts
- src/init/variables/extractors/BaseUrlExtractor.ts
- src/init/variables/extractors/KeyExtractor.ts
- src/init/variables/extractors/ShorthandExtractor.ts
- test/unit/init/AppRunner.test.ts
- test/unit/init/CliResolver.test.ts
- test/unit/init/variables/CombinedShorthandResolver.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1379
Small PR before the holidays.
Makes the `AppRunner` `create/run` functions do what they were supposed to do after the CLI change. Not sure what happened there since there were some comments indicating this is what they did.
Both these functions now also accept a `Settings` object which is interpreted the same was as a parsed CLI object. So provides flexibility to users calling these functions on what they use.
The main result of changing the call procedure is that all the resolvers are now also run when calling them, causing variables to have the default values (if no settings are provided).
> feat: Accept both Settings and VariableBindings to create an App

- config/app/variables/cli/cli.json
- src/init/cli/CliExtractor.ts
- test/integration/Cli.test.ts
- test/integration/ServerFetch.test.ts
In my previous CLI PR I accidentally broke the server, but none of the integration tests caught it since none of them test the CLI configs. So added a test for this. Changed one integration test to use the `AppRunner` to start the server for similar reasons.
Also changed the default CLI config to have strict CLI parsing. This was disabled when moving the CLI interpretation to a config since it could also receive unknown parameters from the first step, such as `mainModulePath`, but at some point those were also added to the config (so they appear in the help) so strict parsing no longer breaks on these. I want to enable strict parsing so when we move specific CLI params to specific configs, this immediately tells the user that the given parameter is not applicable for what they're trying …
> Add CLI integration tests

- RELEASE_NOTES.md
- config/http/README.md
- config/http/server-factory/https-no-websockets.json
- config/http/server-factory/https-websockets.json
- config/http/server-factory/https/cli.json
- config/http/server-factory/https/resolver.json
- config/https-file-cli.json
Moves all the stuff that enables extra CLI params for an HTTPS server to an import option, making it easier to combine with other custom configurations (e.g., mashlib recipe).
I don't really like how HTTP/HTTPS is tied to websockets/no-websockets, but splitting those up would require a larger refactor which would have an impact on existing configs so perhaps something for the future.
Sort of an example of how we can move other CLI params to specific imports in the future (`rootFilePath`, `sparqlEndpoint`, etc.).
> refactor: Add imports that allow for HTTPS through CLI params

- documentation/markdown/client-credentials.md
None
The link in the documentation of Client Credentials to the Identity Provider section goes to Dependency Injection instead. This PR fixes this.
> docs: Fix link to Identity Provider section

- RELEASE_NOTES.md
- src/pods/generate/variables/Variables.ts
- src/util/Vocabularies.ts
Caused by discussion at https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1388#discussion_r930262263
Updates `Vocabularies.ts` with more precise typings so they can be used as type guards together with some utility types.
`VocabularyLocals<typeof AS>` is `"Create" | "Delete" | "Update"`
`VocabularyValues<typeof AS>` is `AS.Create | AS.Delete | AS.Update` is `"https://www.w3.org/ns/activitystreams#Create" | "https://www.w3.org/ns/activitystreams#Delete" | "https://www.w3.org/ns/activitystreams#Update"`
`VocabularyTerms<typeof AS>` is `AS.terms.Create | AS.terms.Delete | AS.terms.Update` is `NamedNode<"https://www.w3.org/ns/activitystreams#Create"> | NamedNode<"https://www.w3.org/ns/activitystreams#Delete"> | NamedNode<"https://www.w3.org/ns/activitystreams#Update">`
> feat: Improve vocabulary typings

- .github/workflows/ci.yml
The idea of this PR is to update the ci pipeline so that mkdocs are being rebuild and updated on every push on the main branch. It is done by splitting it in to 2 jobs. 
The first one is just renamed from the old one and will handle tags (new `major.x` version is being pushed for the docs)
The second one will parse the `versions.json` file that is being hosted, and use jq to query the latest version name. It will then use that version name to update the existing docs.
> Build mkdocs on every push on the main branch

- src/util/Vocabularies.ts
- test/unit/util/Vocabularies.test.ts
Allows vocabularies to be extended. Can be useful for external modules that want to use one of our vocabularies but want to add an extra field to it (which is the case in https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1000 for example). This depends on the breaking type changes so is part of the v6 branch. After this PR is merged I might also add the same in the main branch so it can be a feature release and already be used.
> feat: Allow vocabularies to be extended

- src/identity/configuration/IdentityProviderFactory.ts
- test/integration/Identity.test.ts
- test/unit/identity/configuration/IdentityProviderFactory.test.ts
https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1061
I discovered yesterday that the `renderError` function that we provide to the OIDC library does not always get called when an HTTP request causes an error. Only in cases where HTML is preferred and some other cases. The hack introduced in this PR makes it so it also gets called in other cases so we have full control over the error output. The comments in the code add more explanation.
We had an integration test that checked this, but apparently that happened to be one of those cases where the `renderError` function did get called even though no HTML accept header was sent.
> fix: Always render OIDC errors correctly

- README.md
- config/app/variables/cli/cli.json
- src/init/AppRunner.ts
- test/integration/Cli.test.ts
- test/unit/init/AppRunner.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1430
Doing some smaller issues as I didn't want to immediately jump into something big after ACP 😄.
This change is non-breaking so can target main.
The main advantage of this change is that if you, for example, want to update the locker timeout, you can just have the following config:
```json
{
"@context": "https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/^5.0.0/components/context.jsonld",
"@graph": [
{
"@type": "Override",
"overrideInstance": { "@id": "urn:solid-server:default:ResourceLocker" },
"overrideParameters": {
"@type": "WrappedExpiringReadWriteLocker",
"expiration": 10000
}
}
]
}
```
and then start the server with `npm start -- -c @css:config/file.json my-config.json`. Where …
> Allow multiple configurations to be used during startup

- RELEASE_NOTES.md
- config/app/setup/handlers/setup.json
- config/app/setup/optional.json
- config/app/setup/required.json
- config/default.json
- config/file-no-setup.json
- config/file.json
- config/identity/registration/enabled.json
- config/memory-subdomains.json
- config/path-routing.json
- config/sparql-endpoint-no-setup.json
- config/sparql-endpoint.json
- documentation/markdown/usage/identity-provider.md
- src/identity/interaction/email-password/util/RegistrationManager.ts
- src/init/setup/SetupHttpHandler.ts
- templates/identity/email-password/register-partial.html.ejs
- templates/identity/email-password/register.html.ejs
- templates/setup/input-partial.html.ejs
- test/unit/identity/interaction/email-password/util/RegistrationManager.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1205 and https://github.com/CommunitySolidServer/CommunitySolidServer/issues/570 (or at least prevents most common causes).
Modifies the setup and default configs so we no longer provide an easy option to have data in the root folder while it is also possible to register pods. This way we prevent storages from being nested in each other. The memory-based configs still have this issue since their configs always initialize the root, but it seemed like less of an issue there as those would mostly be used to play around with.
One disadvantage is that the setup page now always prevents adding data in the root when registration is enabled, but in fact this is no problem if you're using subdomain identifiers since there …
> fix: Prevent accidental nested storages

- package-lock.json
- package.json
- src/storage/conversion/RdfToQuadConverter.ts
- test/assets/contexts/test.jsonld
- test/unit/storage/conversion/RdfToQuadConverter.test.ts
Preparation for notification support. The spec requires both a JSON-LD representation and a turtle representation: https://solidproject.org/TR/notifications-protocol#discovery
But the JSON-LD context doesn't exist yet, so we will need to have a local version of it if we want to be able to automatically convert to turtle.
Besides that there are probably also other use cases that would find this useful. Might just be nice to not have to do an HTTP request every time we want to convert from JSON-LD.
> feat: Allow JSON-LD contexts to be stored locally

- .github/workflows/stale.yml
Ading the stale action to mark abandoned issues and close them after a set amount of time:
Current configuration:
- `🏚️ abandoned` Label added after 30 days
- Close abandoned issues after another 30 days (60 days of total inactivity)
- Issues with an assignee are exempted
- Exempted labels:
- `🐛 bug`
- `☀️ enhancement`
- `📚 documentation`
- `➕ feature`
- `🐌 performance`
- `➕ test`
- `📝 task`
- `:ant: worker threads`
- `👩🏾‍💻 developer experience`
Chose to use `abandoned` as a keyword cause I found that several repos default to this and seems more descriptive to me. Can change it to `stale` if wanted.
* …
> Add stale action: mark issues as 🏚️ abandoned and auto close them

- src/util/locking/RedisLocker.ts
- test/unit/util/locking/RedisLocker.test.ts
* #1487 
This PR extends the constructor signature of the RedisLocker class with an extra argument `namespacePrefix`. This will default to the empty string, making it backwards compatible with current CSS instances using the RedisLocker.
Since keys in RedisLocker are SHA-1 hashes of paths, they were subject to clashing with each other. This change should mitigate this issue. Keys that are generated in Redis, will now be prefixed with this string, effectively namespacing them. This allow a single Redis instance to be used by multiple CSS setups (that might be used for different use cases). 
* semver.major: …
> feat: add support for key namespacePrefixes in a RedisLocker instance

- config/ldp/modes/default.json
- src/authorization/permissions/DeleteParentExtractor.ts
- src/index.ts
- test/integration/PermissionTable.test.ts
- test/unit/authorization/permissions/DeleteParentExtractor.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1489
On the one hand it's unfortunate that we need a class for this very specific case. On the other hand it's nice that we can easily inject one in there.
> fix: Return correct status code when deleting non-existent resource

- src/util/locking/RedisLocker.ts
- test/unit/util/locking/RedisLocker.test.ts
https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1491
Added a new parameter called `RedisSettings` to `RedisLocker`. This parameter also allows for easily adding extra options in the future. Also added the existing `namespacePrefix` parameter to this interface.
I created a new PR for this because my pc started acting up doing a rebase. (code based on PR https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1493)
> feat: add additional redis settings to redis locker

- config/ldp/modes/default.json
- src/authorization/permissions/CreateModesExtractor.ts
- src/index.ts
- test/integration/PermissionTable.test.ts
- test/unit/authorization/permissions/CreateModesExtractor.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1467
Makes sure PATCH requests always require `create` permissions.
This has an impact on some of our output status codes as can be seen in the `PermissionTable` test. An alternative would be to go against what the spec says and not always create a resource if it does not exist. This would require some more drastic changes in the patchers though.
A third option would be to disallow empty PATCHes, but we explicitly allowed them for an issue: https://github.com/CommunitySolidServer/CommunitySolidServer/issues/759
With this change, the `resourceSet` parameters could be removed from the sparql/n3patch modes extractors, as they do the same check if there is an input body, but that would break their interface and I …
> Require "create" permission for empty PATCH bodies

- bin/server.js
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/314
The `uncaughtExceptionMonitor` is an event that is emitted right before an `uncaughtException` specifically to allow you to log it.
> chore: Log uncaught exceptions

- README.md
- config/app/init/initializers/server.json
- config/app/variables/cli/cli.json
- config/app/variables/resolver/resolver.json
- config/util/variables/default.json
- src/init/ServerInitializer.ts
- src/init/variables/extractors/BaseUrlExtractor.ts
- src/server/BaseHttpServerFactory.ts
- src/server/HttpServerFactory.ts
- src/server/WebSocketServerFactory.ts
- test/integration/Config.ts
- test/unit/init/ServerInitializer.test.ts
- test/unit/init/variables/extractors/BaseUrlExtractor.test.ts
- test/unit/server/BaseHttpServerFactory.test.ts
- test/util/Util.ts
closes #1104 
Introduces `--socket` argument to let the server listen on Unix Domain Socket instead of TCP sockets.
> feat: allow server to bind to Unix Domain Sockets

- RELEASE_NOTES.md
- documentation/markdown/README.md
- documentation/markdown/usage/dev-configuration.md
- src/init/AppRunner.ts
- test/unit/init/AppRunner.test.ts
Supercedes #1499 targeting main
> feat [semver.minor]: allow css configuration from package.json or config file

- src/init/cli/YargsCliExtractor.ts
- test/unit/init/cli/YargsCliExtractor.test.ts
https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1418
Add yargs argument check to display useful error to the user when multiple values were given for the same non array type parameter/variable.
⬆️  Not sure about this one. If this is supposed to be merged into `main` I'ill create another PR because my laptop really does not like a rebase for some reason.
> feat: return clear error when multiple values for a cli flag are given

- RELEASE_NOTES.md
- config/sparql-file-storage.json
- config/storage/backend/regex.json
- config/storage/backend/sparql.json
- src/storage/RepresentationConvertingStore.ts
- test/unit/storage/RepresentationConvertingStore.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/297
Apparently this is possible now (and probably was for some time), although the configuration is less pretty.
The `metadataStrategy` field is because of https://github.com/CommunitySolidServer/CommunitySolidServer/commit/f7742cffefa2875442798a478a5d7a9960dbfa7e
> feat: Take preferences as input in `RepresentationConvertingStore`

- config/storage/key-value/storages/storages.json
- src/index.ts
- src/storage/keyvalue/EncodingPathStorage.ts
- src/storage/keyvalue/HashEncodingPathStorage.ts
- test/unit/storage/keyvalue/HashEncodingPathStorage.test.ts
Makes it so the generated locks can no longer trigger the issue in https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1013
I spent too much time on this as to get to the solution I want would require a more comprehensive rewrite of the internal storage system, but I don't want to spend time on that currently, so I got somewhere stuck in-between. In the end I made the minimal changes necessary to just make sure this doesn't prevent users from using the CSS as the locks tended to be the most common cause of this.
This new storage can only be used for locks for now, as changing the other internal storages would break existing installations. Locks are cleared on server restart so there it doesn't matter that the format changes.
> feat: Hash lock-related identifiers

- src/init/SeededPodInitializer.ts
- test/unit/init/SeededPodInitializer.test.ts
Closes #1561 
Added a try-catch block to log warnings instead of throwing exceptions in SeededPodInitializer
> feat: SeededPodInitializer log exceptions as warning instead of crashing

- src/identity/configuration/IdentityProviderFactory.ts
- templates/error/descriptions/E0003.md.hbs
- test/unit/identity/configuration/IdentityProviderFactory.test.ts
https://github.com/inrupt/solid-client-authn-js/issues/2088
Shows a clearer error message in case the authorizing client is unknown. This mostly happens when experimenting with new CSS instances but the client stored information in the browser that is no longer relevant. Picture below of what the output of the template looks like.
> feat: Provide clear error message for unknown clients

- src/identity/configuration/IdentityProviderFactory.ts
- src/index.ts
- src/storage/conversion/ErrorToJsonConverter.ts
- src/util/errors/OAuthHttpError.ts
- test/integration/Identity.test.ts
- test/unit/identity/configuration/IdentityProviderFactory.test.ts
- test/unit/storage/conversion/ErrorToJsonConverter.test.ts
- test/unit/util/errors/OAuthHttpError.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1586
So turns out an OIDC server needs to add specific fields to the error output if something goes wrong and I removed that by piping all errors to our error converter pipeline. This makes sure the requires fields are back. This is done in such a way so the error conversion part of the code has no references to the OIDC library, which could be relevant if we ever split off the OIDC part.
> fix: Output required OAuth error fields

- config/identity/handler/account-store/default.json
- config/identity/ownership/token.json
- config/ldp/authorization/readers/access-checkers/agent-group.json
- src/storage/keyvalue/WrappedExpiringStorage.ts
- test/unit/storage/keyvalue/WrappedExpiringStorage.test.ts
(https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1456)
CSS Version: 5.1.0
Required to remove all classes which implemented the Finalizable interface only to ensure a timer was cleared in the .finalize() implementation, and replace it with a timer.unref() call after the timer is created. The references to the Finalizable Handlers were removed from the configuration files. The tests associated with the changed classes were updated where errors occurred in the test suite. To the best of my knowledge, this only occurred in the WrappedExpiringStorage class. 
* semver.major: Breaking changes. This …
> fix: updated WrappedExpiringStorage tests and timer.unref calls

- src/identity/configuration/CachedJwkGenerator.ts
- test/unit/identity/configuration/CachedJwkGenerator.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1558
In v5.0 and before we stored keys as a JWKS so we need to keep doing this to be backwards compatible.
> fix: Store internal JWK as JWKS to be backwards compatible

- src/http/ldp/GetOperationHandler.ts
- src/http/ldp/HeadOperationHandler.ts
- src/storage/BasicConditions.ts
- src/storage/Conditions.ts
- src/storage/DataAccessorBasedStore.ts
- src/util/ResourceUtil.ts
- test/integration/Conditions.test.ts
- test/unit/http/ldp/GetOperationHandler.test.ts
- test/unit/http/ldp/HeadOperationHandler.test.ts
- test/unit/http/output/metadata/ModifiedMetadataWriter.test.ts
- test/unit/storage/BasicConditions.test.ts
- test/unit/storage/Conditions.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
- test/unit/util/ResourceUtil.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1605
Makes the ETag representation specific by adding the content-type (after content negotiation).
> fix: Ensure the ETag is representation specific

- config/util/resource-locker/file.json
- src/util/locking/FileSystemResourceLocker.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1610
See https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1610#issuecomment-1512948344
Use the `EqualReadWriteLocker` instead of the `GreedyReadWriteLocker` to make sure that locks always get released by the worker thread that acquired the lock.
> fix: Use EqualReadWriteLocker with file locker to prevent deadlocks

- config/http/notifications/base/handler.json
- src/http/ldp/PostOperationHandler.ts
- src/http/representation/RepresentationMetadata.ts
- src/index.ts
- src/server/notifications/ActivityEmitter.ts
- src/server/notifications/ListeningActivityHandler.ts
- src/server/notifications/NotificationHandler.ts
- src/server/notifications/generate/AddRemoveNotificationGenerator.ts
- src/storage/DataAccessorBasedStore.ts
- src/storage/MonitoringStore.ts
- src/util/Vocabularies.ts
- test/integration/WebSocketChannel2023.test.ts
- test/unit/http/UnsecureWebSocketsProtocol.test.ts
- test/unit/http/ldp/PostOperationHandler.test.ts
- test/unit/server/notifications/ListeningActivityHandler.test.ts
- test/unit/server/notifications/generate/AddRemoveNotificationGenerator.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
- test/unit/storage/MonitoringStore.test.ts
- test/util/NotificationUtil.ts
https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1388#issuecomment-1378651775
Introduces 2 new notification types: Add and Remove. These are emitted on containers and indicate that a resource was created or deleted in the container.
This required some change in how we pass data from the `MonitoringStore`. I decided to just also emit the metadata object so this can be used to provide more information about the change that is taking place.
> Use Add/Remove notifications for containers

- documentation/markdown/README.md
- documentation/markdown/usage/notifications.md
- documentation/mkdocs.yml
https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1565 and https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1566
Documentation about how to use the notifications after the changes in the PRs above. Some of this is duplication of what is in the spec, but it seemed like a good idea to have a document users can reference to see how to use notifications on CSS. Since the notification spec is still changing fast this might also help to just have a document describing the current state in CSS if we haven't updated to the latest changes yet.
> docs: Describe how notifications work on the server

- src/server/notifications/ComposedNotificationHandler.ts
- src/storage/BasicConditions.ts
- src/storage/Conditions.ts
- test/unit/server/notifications/ComposedNotificationHandler.test.ts
- test/unit/storage/Conditions.test.ts
Fixed an issue with the ETag being used for the state of notifications, caused by merging the new ETag format of the main branch into the v6.0.0 branch with notifications. Also fixes some edge case issues when there is no content type.
> fix: Support new ETag format in notification states

- config/http/README.md
- config/http/notifications/new-old-websockets.json
- config/http/notifications/websockets/http.json
- config/http/server-factory/configurator/default.json
- src/http/UnsecureWebSocketsProtocol.ts
- src/index.ts
- src/server/WebSocketHandler.ts
- src/server/WebSocketServerConfigurator.ts
- src/server/notifications/WebSocketChannel2023/WebSocket2023Listener.ts
- src/server/notifications/WebSocketChannel2023/WebSocket2023Util.ts
- src/server/notifications/WebSocketChannel2023/WebSocketChannel2023Type.ts
- test/integration/WebSocketChannel2023.test.ts
- test/unit/http/UnsecureWebSocketsProtocol.test.ts
- test/unit/server/WebSocketServerConfigurator.test.ts
- test/unit/server/notifications/WebSocketChannel2023/WebSocket2023Listener.test.ts
- test/unit/server/notifications/WebSocketChannel2023/WebSocket2023Util.test.ts
- test/unit/server/notifications/WebSocketChannel2023/WebSocketChannel2023Type.test.ts
https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1220
Like it says in the title. Allows server to support both the old and new specification simultaneously to potentially have a transitionary period.
There is now 1 class that catches all WebSocket requests and calls its handler, allowing us to combine multiple handlers for specific targets.
Also updates the new WebSocket implementation to just use the channel identifier for the WebSocket instead of using 1 fixed URL with a query parameter.
> Allow server to support both new and old websocket protocols simultaneously

- src/util/errors/HttpErrorUtil.ts
- test/unit/util/errors/HttpErrorUtil.test.ts
- test/unit/util/handlers/BooleanHandler.test.ts
- test/unit/util/handlers/HandlerUtil.test.ts
- test/unit/util/handlers/WaterfallHandler.test.ts
Prevents those error messages that are arrays of commas because none of the errors had a message. Bothered me while working on something else and was an easy fix.
> fix: Make aggregated errors prettier

- RELEASE_NOTES.md
- config/util/resource-locker/file.json
- config/util/resource-locker/memory.json
- src/index.ts
- src/server/AuthorizingHttpHandler.ts
- src/server/WacAllowHttpHandler.ts
- src/util/locking/BaseReadWriteLocker.ts
- src/util/locking/EqualReadWriteLocker.ts
- src/util/locking/GreedyReadWriteLocker.ts
- src/util/locking/PartialReadWriteLocker.ts
- test/integration/Identity.test.ts
- test/unit/util/locking/BaseReadWriteLocker.test.ts
- test/unit/util/locking/GreedyReadWriteLocker.test.ts
- test/unit/util/locking/PartialReadWriteLocker.test.ts
https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1617 changed the file locker configuration to no longer use the `GreedyReadWriteLocker` as the file locker library that we use only allows locks to be released by the same thread that acquired them.
This caused breakage in the 6.0.0 branch as changes in the `WacAllowMetadataWriter` sometimes cause it to request a read lock on the resource the request is targeting. This means that there already is an active read lock causing the request to get stuck since the `WacAllowMetadataWriter` doesn't get its lock, but it also never gets released since nobody can read the data from the output stream yet.
The `PartialReadWriteLocker` introduced in this PR is very similar to the `GreedyReadWriteLocker` except that it only allows …
> fix: Make sure locker allows reentrant lock acquisition

- RELEASE_NOTES.md
- config/app/README.md
- config/app/init/initialize-prefilled-root.json
- config/app/init/initialize-root.json
- config/app/init/static-root.json
- src/server/middleware/StaticAssetHandler.ts
- test/unit/server/middleware/StaticAssetHandler.test.ts
As the title says. This makes it easy to set the root container to a static file instead of a Solid resource, preventing overlapping storages when registration is enabled while still showing something when the root is accessed.
The IDP refactor will probably remove everything setup related so this will also be useful to make sure users still see something when they boot up a server.
> Allow StaticAssetHandler to link a container to a single file

- src/util/PathUtil.ts
- test/unit/util/PathUtil.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1653
Prevents file paths from having potential illegal characters by always encoding them.
> fix: Prevent illegal file paths from being generated

- config/http/handler/default.json
- config/http/handler/simple.json
Provides ids for some some blank nodes in the config so that they can be overriden.
> chore: name http handlers

- src/http/output/metadata/AllowAcceptHeaderWriter.ts
- test/unit/http/output/metadata/AllowAcceptHeaderWriter.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1666
Only allows PUT on existing containers. Also fixes inconsistency in how the check was done for POST.
> Do not show PUT in Allow header for existing containers

- RELEASE_NOTES.md
- src/init/AppRunner.ts
- test/integration/ServerFetch.test.ts
- test/unit/init/AppRunner.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1539
Disables type checking in Components.js for everything. Also makes it so config parameters are expanded when creating the server through code.
> fix: Make all ways to start the server more consistent

- jest.config.js
- test/integration/WebHookChannel2023.test.ts
- test/integration/WebSocketChannel2023.test.ts
- test/unit/logging/WinstonLoggerFactory.test.ts
- test/util/SetupTests.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1452 and closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1479
I no longer seem to be able the first issue so it seems to be solved.
For the second issue, the jest config was changed so `SetupTests.ts` only triggers once, before all tests. This caused the logger factory to not have full test coverage any more through the tests so some had to be added.
> Integration test fixes

- .github/workflows/docker.yml
#1697
This PR adds `linux/arm64/v8` to the platforms to add support for Apple Silicon architectures.
> ci: Add `linux/arm64/v8` as platform to support Apple Silicon architectures

- test/unit/storage/mapping/FixedContentTypeMapper.test.ts
This is a fix to the typo discovered by @TallTed in the test that I added in #1704. This ideally should have been fixed in the PR, but I did not see it for some reason and it was merged already. Sorry about that.
> Chore: Fix typo in test description

- .componentsignore
- .eslintrc.js
- src/index.ts
- src/pods/generate/BaseResourcesGenerator.ts
- src/storage/accessors/InMemoryDataAccessor.ts
- src/storage/keyvalue/IndexedStorage.ts
- src/storage/keyvalue/JsonFileStorage.ts
- src/storage/keyvalue/WrappedIndexedStorage.ts
- src/util/locking/MemoryResourceLocker.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
- test/unit/storage/keyvalue/WrappedIndexedStorage.test.ts
- test/unit/util/locking/BaseReadWriteLocker.test.ts
- test/unit/util/locking/RedisLocker.test.ts
- test/util/Util.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1450 (at least partially).
Introduces a new way to store internal data. The new interface allows for more complex queries on the data and is designed in such a way that a component with an actual DB backend could be made. The file-based implementation added here has some restrictions but is sufficient for now for what is needed for https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1677. This storage is not used anywhere in this PR, that will be added in the account PR.
> Introduce IndexedStorage for a more extensive storage solution

- src/storage/keyvalue/EncodingPathStorage.ts
- test/unit/storage/keyvalue/EncodingPathStorage.test.ts
Accidentally discovered this issue. The internal key/value storage uses base64 encoding on the keys before writing them to the backend. The issue is now that that encoding could contain `=` symbols for padding, which will be converted to `%3D` in the backend. When requesting all the keys in the storage that means the returned keys will be, for example, `YXBwbGU%3D` instead of `YXBwbGU=`, which will be decoded to `apple7` instead of `apple`. And if you use that key again on the same storage there will be no match.
This is only relevant on the `entries` call of the storage, as that is the only one that returns a list of keys, which explains why this issue has not yet been noticed. The only time this is currently being used is when iterating over all entries in the storage to delete expired …
> fix: Remove URL encoding from base64 strings before decoding

- .github/workflows/npm-test.yml
- README.md
- RELEASE_NOTES.md
- documentation/markdown/usage/starting-server.md
- package-lock.json
- package.json
- src/http/auxiliary/RoutingAuxiliaryStrategy.ts
- tsconfig.json
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1637
Adds Node 20 testing and makes Node 18 the minimum supported version. The reason for also immediately cutting of Node 16 is that oidc-provider v8 only supports Node 18 and up.
> Make node v18 the minimum supported version

- jest.config.js
- test/integration/Quota.test.ts
- test/util/TeardownTests.ts
CI kept failing quite often on the quota integration test. E.g., https://github.com/CommunitySolidServer/CommunitySolidServer/actions/runs/6420125694/job/17432588104?pr=1662
This fixes the issue by delaying the cleanup until later.
> Prevent integration test failing during CI

- src/server/AuthorizingHttpHandler.ts
- src/util/Vocabularies.ts
- test/unit/server/AuthorizingHttpHandler.test.ts
No related issue. Discussed in person with @joachimvh.
This PR makes the AuthorizingHttpHandler add the data of the AccessMap (requested modes and targets) to the RepresentationMetadata in case of an UnauthorizedError (401).
> Feat: pass requestedModes metadata on 401

- package-lock.json
- package.json
- src/identity/interaction/account/util/BaseLoginAccountStorage.ts
- test/deploy/tsconfig.json
- test/tsconfig.json
Upgrades TypeScript to v5.2.2. Had to do some tsconfig shenanigans in the test folders to make sure `jest` could still handle the esm dependencies without breaking our deploy script for the CTH.
> chore: Update to TypeScript 5.2.2

- templates/scripts/util.js
Discovered in https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1757
When changing the linting settings in https://github.com/CommunitySolidServer/CommunitySolidServer/commit/6248ed093813e95255f031eb8fcc37e4d869235c, `util.js`, which is used in the account pages, broke because of some the changes introduced there. This PR reverts those changes.
> fix: Undo util.js errors introduced when changing lint settings

- src/init/migration/SingleContainerJsonStorage.ts
- src/storage/keyvalue/JsonResourceStorage.ts
- test/assets/migration/v6/.internal/setup/aW52YWxpZFJlc291cmNl$.json
- test/integration/V6Migration.test.ts
- test/unit/init/migration/SingleContainerJsonStorage.test.ts
- test/unit/storage/keyvalue/JsonResourceStorage.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1757
Although invalid JSON resources shouldn't occur if everything goes fine, the server also shouldn't stop processing if they do find one.
PR prevents this issue both for migration and general storage usage.
> Prevent storage issues with invalid JSON resources

- documentation/markdown/usage/client-credentials.md
Explicitly link to the relevant API steps describing how to log in, which is needed for client credentials.
> docs: Explain that users need to log in for client credentials

- .github/workflows/docker.yml
https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1761
Arm builds are preventing the Docker build from succeeding. This way we at least still build the linux/amd64 Docker build until https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1761 can be resolved.
> chore: Remove Docker arm builds

- src/authorization/permissions/MethodModesExtractor.ts
- test/integration/PermissionTable.test.ts
- test/unit/authorization/permissions/MethodModesExtractor.test.ts
Closes #1822 
Update the modes extractor to require append + create if the target of a PUT does not exist, instead of write + create.
> fix: Only require append when creating with PUT

- src/identity/ownership/TokenOwnershipValidator.ts
- test/integration/Accounts.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1821
Due to the keys not being encoded it was actually impossible to generate ownership tokens when using a file backend.
> fix: Encode WebID ownership tokens

- documentation/markdown/usage/client-credentials.md
Add some clarity for new users on how the default email/password login API can be used when trying to generate credentials tokens.
> docs: Add login example to credentials documentation

- src/pods/generate/BaseResourcesGenerator.ts
- test/unit/pods/generate/BaseResourcesGenerator.test.ts
Accidentally discovered this. When having predefined templates to initialize a container/pod, the content-type metadata gets lost if there is a metadata template.
> fix: Keep content-type when using metadata templates

- src/identity/interaction/InteractionUtil.ts
- test/unit/identity/interaction/InteractionUtil.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1842
The problem was the oidc-provider library wanting to reuse the grant that was created for the previous account/WebID.
> fix: Prevent error when switching accounts

- src/pods/generate/SubdomainIdentifierGenerator.ts
- test/unit/pods/generate/SubdomainIdentifierGenerator.test.ts
Discovered in https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1852
When using subdomains, the root container can be used as a pod even if there are other pods on the server, as in this case the pods are not contained within the root container.
> fix: Extract root as possible pod when using subdomains

- src/storage/conversion/RdfToQuadConverter.ts
- test/unit/storage/conversion/RdfToQuadConverter.test.ts
Closes #1866 
After this change, `Accept: text/turtle, */*;q=0.5` on a markdown document will return the markdown, while `Accept: text/turtle, */*;q=0.1` will (try to) convert the markdown to turtle through RDFa.
> fix: Add priorities to RDF types when converting

- src/storage/mapping/BaseFileIdentifierMapper.ts
- test/unit/storage/mapping/BaseFileIdentifierMapper.test.ts
- test/unit/storage/mapping/ExtensionBasedMapper.test.ts
- test/unit/storage/mapping/FixedContentTypeMapper.test.ts
This was causing issues with paths like `/foo/...bar`. The restrictions are there to prevent potential issues when converting to a file path, but the ones we had were too strict.
> fix: Allow path segments to start with 2 or more dots

- config/ldp/handler/components/error-handler.json
- src/http/output/error/TargetExtractorErrorHandler.ts
- src/http/output/metadata/AllowAcceptHeaderWriter.ts
- src/http/output/metadata/AuxiliaryLinkMetadataWriter.ts
- src/index.ts
- src/util/Vocabularies.ts
- src/util/handlers/StaticThrowHandler.ts
- test/integration/LdpHandlerWithoutAuth.test.ts
- test/unit/http/output/error/TargetExtractorErrorHandler.test.ts
- test/unit/http/output/metadata/AllowAcceptHeaderWriter.test.ts
- test/unit/http/output/metadata/AuxiliaryLinkMetadataWriter.test.ts
- test/unit/util/handlers/StaticThrowHandler.test.ts
- test/util/FetchUtil.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1877
Adds a new error handler that stores the original target in the error metadata. This way we can close the linked issue and also have more accurate Allow headers.
> Add target metadata to errors

- src/util/identifiers/BaseIdentifierStrategy.ts
- test/unit/util/identifiers/BaseIdentifierStrategy.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1889
Replace URL constructor logic with regex to have consistent results. The test with double slashes was added to keep behaviour there consistent with how it was before this.
> fix: Make `getParentContainer` work with query parameters

- src/server/notifications/StreamingHttpChannel2023/StreamingHttp2023Emitter.ts
- src/server/notifications/StreamingHttpChannel2023/StreamingHttpRequestHandler.ts
- test/unit/server/notifications/StreamingHttpChannel2023/StreamingHttp2023Emitter.test.ts
- test/unit/server/notifications/StreamingHttpChannel2023/StreamingHttpRequestHandler.test.ts
I have been getting notifications where most of the turtle is in one chunk, and the final `.` is in a separate chunk.
By using `readableToString,` the HTTP stream is chunked independently of chunks on `representation.data`.
The requirement to have the full notification in a single chunk is not yet in the spec, but I'm tracking it in:
* https://github.com/solid/notifications/issues/46
> fix: Ensure streaming HTTP streams the whole notification in a single chunk

- config/http/notifications/streaming-http.json
- config/http/notifications/streaming-http/http.json
- src/server/notifications/StreamingHttpChannel2023/StreamingHttpMetadataWriter.ts
- src/server/notifications/StreamingHttpChannel2023/StreamingHttpRequestHandler.ts
- test/integration/StreamingHttpChannel2023.test.ts
- test/unit/server/notifications/StreamingHttpChannel2023/StreamingHttpMetadataWriter.test.ts
- test/unit/server/notifications/StreamingHttpChannel2023/StreamingHttpRequestHandler.test.ts
I tried streaming HTTP notifications with the *subdomain* identifier strategy, which, of course, didn't work.
By using the topic's fully encoded IRI now, it should not assume any specific identifier strategy.
> fix: use full encoded topic iri in streaming http receiveFrom url template

- test/deploy/validate-configs.sh
Accidentally discovered through https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1943
The `*` should not be there and actually caused the files not to be deleted.
> Correctly delete data in validate-configs.sh

- config/http/middleware/handlers/constant-headers.json
- config/storage/middleware/default.json
- src/storage/BinarySliceResourceStore.ts
- test/unit/storage/BinarySliceResourceStore.test.ts
Fixes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1948
Firefox and Chrome both use range headers with ambiguous endings to stream video (for example `range: 0-` rather than `range: 0-5000000`). As built, CSS was trying to deliver an entire video in a single request because of this. This lead to long load times for large videos.
I followed the solution posed by Zeng Xu (https://www.zeng.dev/post/2023-http-range-and-play-mp4-in-browser/) and arbitrarily added a default number of bytes to deliver if the byte range end wasn't provided. This works on Firefox, Chrome, and Safari.
Unfortunately, this does break RFC 7233 (https://www.rfc-editor.org/rfc/rfc7233#section-2.1), but as of this moment, it is the only way I found to get streaming video to work on Firefox and …
> fix: streaming video by adding a limit to streaming chunks

- config/ldp/handler/components/error-handler.json
- src/http/output/error/EmptyErrorHandler.ts
- src/index.ts
- src/util/ResourceUtil.ts
- src/util/Vocabularies.ts
- test/integration/Conditions.test.ts
- test/unit/http/output/error/EmptyErrorHandler.test.ts
https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1959
See the linked issue for details. Apparently it is easier to just return all the headers of the original response instead of returning none. No extra work is required as we already request the metadata to see if the response needs to be a 304 or not.
> fix: Keep headers for 304 responses

- src/storage/patch/N3Patcher.ts
- src/util/QuadUtil.ts
- test/unit/storage/patch/N3Patcher.test.ts
- test/unit/util/QuadUtil.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1977
I changed the querying step when patching to perform it internally instead of with Comunica, retaining the blank node labels.
> Support patching data containing blank nodes

- src/util/locking/FileSystemResourceLocker.ts
- test/unit/util/locking/FileSystemResourceLocker.test.ts
https://github.com/CommunitySolidServer/Recipes/issues/44#issuecomment-2602605410
Prevents the server from crashing, unless required, when a lock is compromised.
> fix: Prevent server from crashing when a lock is compromised

- templates/identity/account/pod-settings.html.ejs
Fixes https://github.com/CommunitySolidServer/Recipes/issues/46
The HTML page was using the wrong field to add an owner to a pod
> Use the correct field when adding a pod owner

- src/storage/DataAccessorBasedStore.ts
- src/storage/accessors/FileDataAccessor.ts
- test/integration/Conditions.test.ts
- test/unit/storage/DataAccessorBasedStore.test.ts
Discussed in matrix. Problem was that updating metadata did not change the last modified time of a resource, causing the ETag to not update. This was especially a problem for contains whose representation is partially generated by their metadata.
This now updates the last modified time of a resource when the metadata is modified. Since the `FileDataAccessor` uses `mtime` from disk, there we have to take the max of the `mtime` for both the resource itself and its metadata.
> Changing metadata updates a resource's modified time

- src/identity/interaction/routing/IdInteractionRoute.ts
- test/unit/identity/interaction/routing/IdInteractionRoute.test.ts
`IdInteractionRoute` could not match URLs if `ensureSlash` was set to false.
> fix: Correctly match IdInteractionRoutes without trailing slash

- src/pods/generate/SubdomainIdentifierGenerator.ts
- src/pods/generate/SuffixIdentifierGenerator.ts
- templates/identity/account/create-pod.html.ejs
- test/unit/pods/generate/SubdomainIdentifierGenerator.test.ts
- test/unit/pods/generate/SuffixIdentifierGenerator.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1894
Only relevant for subdomain pods as domains are case-insensitive. But for consistency, suffix pods are also changed.
> fix: Force pod names to be lower case

- src/storage/keyvalue/WrappedIndexedStorage.ts
- test/unit/storage/keyvalue/WrappedIndexedStorage.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/2011 (or at least that specific error)
The indexed storage was made with the idea that the structure is defined once and does not change. In case it does, errors like the ones in the linked issue can occur. This PR adds some more robustness to handle some situations like that.
> fix: Make the WrappedIndexedStorage more robust for structure changes

- package-lock.json
- package.json
Not immediately necessary, but users were running into issues where they used the CSS components.js dependency and tried using features that were only added in v5.5.0. This prevents those issues.
> chore: Update Components.js to v5.5.1

- package-lock.json
- package.json
- test/integration/Identity.test.ts
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/pull/2070 and https://github.com/CommunitySolidServer/CommunitySolidServer/pull/2068
> chore(deps-dev): bump @inrupt/solid-client-authn-js from 2.0.0 to 3.1.0
