CommunitySolidServer/CommunitySolidServer

.eslintrc.js
src/ldp/AuthenticatedLdpHandler.ts
src/util/AsyncHandler.ts
src/util/CompositeAsyncHandler.ts
src/util/errors/HttpError.ts
src/util/errors/UnsupportedHttpError.ts
test/index.ts
test/unit/ldp/AuthenticatedLdpHandler.test.ts
test/unit/util/AsyncHandler.test.ts
test/unit/util/CompositeAsyncHandler.test.ts
test/unit/util/errors/UnsupportedHttpError.test.ts
test/util/StaticAsyncHandler.ts

Builds on #3 so will merge after that one.
Changes some eslint settings that were bothering me + the one that forces a space before function brackets.  If there are any other ones that are bothering you, you can add them here.

Update eslint settings

---

src/authentication/SimpleCredentialsExtractor.ts
src/authorization/SimpleAuthorizer.ts
src/ldp/http/BodyParser.ts
src/ldp/http/PreferenceParser.ts
src/ldp/http/SimpleBodyParser.ts
src/ldp/http/SimplePreferenceParser.ts
src/ldp/http/SimpleRequestParser.ts
src/ldp/http/SimpleResponseWriter.ts
src/ldp/http/SimpleTargetExtractor.ts
src/ldp/http/TargetExtractor.ts
src/ldp/operations/SimpleDeleteOperationHandler.ts
src/ldp/operations/SimpleGetOperationHandler.ts
src/ldp/operations/SimplePostOperationHandler.ts
src/ldp/permissions/SimplePermissionsExtractor.ts
src/ldp/representation/NamedRepresentation.ts
src/ldp/representation/RepresentationMetadata.ts
src/util/errors/NotFoundHttpError.ts
src/util/errors/UnsupportedMediaTypeHttpError.ts

This one only contains documentation changes.

fix: add documentation for many classes where it was missing

---

src/ldp/AuthenticatedLdpHandler.ts
src/ldp/http/SimpleBodyParser.ts
src/ldp/http/SimpleResponseWriter.ts
src/server/ExpressHttpServer.ts
test/integration/RequestParser.test.ts
test/unit/ldp/AuthenticatedLdpHandler.test.ts
test/unit/ldp/http/SimpleBodyParser.test.ts
test/unit/ldp/http/SimpleResponseWriter.test.ts
test/unit/server/ExpressHttpServer.test.ts

This fixes 2 specific issues as seen in the commits.

Some bugfixes

---

src/authentication/SimpleCredentialsExtractor.ts
src/authorization/SimpleAuthorizer.ts
src/ldp/http/AcceptPreferenceParser.ts
src/ldp/http/SimpleBodyParser.ts
src/ldp/permissions/SimplePermissionsExtractor.ts
test/unit/server/ExpressHttpServer.test.ts

fix: Remove all instances of `return undefined`

---

src/ldp/http/SimpleResponseWriter.ts
src/server/ExpressHttpServer.ts
src/storage/SimpleResourceStore.ts
test/unit/storage/SimpleResourceStore.test.ts

Use text/plain for errors and return text/turtle by default

---

.eslintrc.js
src/ldp/http/AcceptPreferenceParser.ts
src/ldp/http/ResponseWriter.ts
src/storage/LockingResourceStore.ts
src/storage/PatchingStore.ts
src/storage/SimpleResourceStore.ts
src/storage/patch/SimpleSparqlUpdatePatchHandler.ts
src/util/AcceptParser.ts
src/util/CompositeAsyncHandler.ts
test/integration/AuthenticatedLdpHandler.test.ts
test/unit/ldp/AuthenticatedLdpHandler.test.ts
test/unit/ldp/http/AcceptPreferenceParser.test.ts
test/unit/ldp/http/SimpleResponseWriter.test.ts
test/unit/ldp/http/SimpleSparqlUpdateBodyParser.test.ts
test/unit/ldp/http/SimpleTargetExtractor.test.ts
test/unit/ldp/operations/SimpleDeleteOperationHandler.test.ts
test/unit/ldp/operations/SimplePostOperationHandler.test.ts
test/unit/server/ExpressHttpServer.test.ts
test/unit/storage/LockingResourceStore.test.ts
test/unit/storage/SimpleResourceStore.test.ts
test/unit/storage/patch/SimpleSparqlUpdatePatchHandler.test.ts
test/unit/util/AcceptParser.test.ts
test/unit/util/CompositeAsyncHandler.test.ts

Resolves #40
The exception for URLs is (currently) for [this](https://github.com/solid/community-server/blob/master/src/server/ExpressHttpServer.ts#L17) line. But made sense to allow that imo.

fix: Set max-len to 120

---

src/ldp/http/SimpleBodyParser.ts
src/ldp/http/SimpleResponseWriter.ts
src/storage/SimpleResourceStore.ts
src/storage/patch/SimpleSparqlUpdatePatchHandler.ts
src/util/ContentTypes.ts
test/integration/RequestParser.test.ts
test/unit/ldp/http/SimpleBodyParser.test.ts
test/unit/ldp/http/SimpleResponseWriter.test.ts
test/unit/ldp/operations/SimpleGetOperationHandler.test.ts
test/unit/storage/SimpleResourceStore.test.ts
test/unit/storage/patch/SimpleSparqlUpdatePatchHandler.test.ts

feat: Specifiy constants in separate file

---

package-lock.json

This was due to a weird (and incorrect) implementation of the RDF/JS `import` method.

fix: reset lockfile to update to fixed JSON-LD serializer, Closes #105

---

src/server/ExpressHttpServer.ts
test/unit/server/ExpressHttpServer.test.ts

Plus a little fix that popped up because of symmetry.

Send server identification

---

src/ldp/http/RawBodyParser.ts
test/integration/AuthenticatedLdpHandler.test.ts
test/integration/Authorization.test.ts
test/integration/RequestParser.test.ts
test/unit/ldp/http/RawBodyParser.test.ts

Depends on https://github.com/solid/community-server/issues/122
Fixes https://github.com/solid/community-server/issues/121

Determine body presence according to RFC7230

---

package.json

Closes https://github.com/solid/community-server/issues/124

Add package metadata

---

README.md

Closes https://github.com/solid/community-server/issues/29

Add context to README

---

.travis.yml
.travis/validate-package.sh

Small bin validator as suggested here: https://github.com/solid/community-server/pull/99#issuecomment-684604086

feat: add package validator to CI

---

src/storage/FileResourceStore.ts
src/storage/conversion/RdfToQuadConverter.ts
src/util/MetadataController.ts
src/util/Util.ts
test/unit/storage/FileResourceStore.test.ts

Rebase of #77 since I didn't want to push to their master branch

Freyavs master

---

.travis/validate-package.sh

The current deployment test would piggy-back on the existing `node_modules` instead of installing its own, and as such was not a good test to see if the main dependencies are there (https://github.com/solid/community-server/issues/132).
I've reorganized the script to make this happen.

Make deployment test install packages

---

package-lock.json
package.json
src/storage/PassthroughStore.ts
src/storage/PatchingStore.ts
src/storage/RepresentationConvertingStore.ts

As discussed in https://github.com/solid/community-server/issues/137

Make PassthroughStore generic

---

jest.config.js
test/unit/init/CliRunner.test.ts

This closes #166.
It seems like the mocking does not work and I'm not sure why.
other attempts at mocking can be found here: https://paste.smessie.com/rexoyolune.js and https://paste.smessie.com/jepohabeku.js but both are still failing.

test: Write unit tests for CliRunner

---

src/storage/accessors/FileDataAccessor.ts
test/unit/storage/accessors/FileDataAccessor.test.ts

fix: Remove metadata file if no new metadata is stored

---

src/ldp/http/BasicResponseWriter.ts
test/unit/ldp/http/BasicResponseWriter.test.ts

This PR:
- closes #120
- closes #83

Resolves duplicate error message and no trailing newline

---

.eslintrc.js
package-lock.json
src/ldp/representation/RepresentationMetadata.ts
src/logging/WinstonLoggerFactory.ts
src/storage/DataAccessorBasedStore.ts
src/storage/accessors/InMemoryDataAccessor.ts
src/storage/conversion/ChainedConverter.ts
src/storage/conversion/QuadToRdfConverter.ts
src/storage/conversion/RdfToQuadConverter.ts
src/storage/conversion/TypedRepresentationConverter.ts
src/util/HeaderUtil.ts
src/util/UriUtil.ts
test/unit/storage/DataAccessorBasedStore.test.ts
test/unit/storage/ExtensionBasedMapper.test.ts
test/unit/storage/conversion/ChainedConverter.test.ts

Adding this for review since stylistic updates were required.
It is annoying though that linter rules introduce breaking changes within semver.

Update all dependencies

---

.eslintrc.js
package-lock.json
package.json
test/.eslintrc.js
test/unit/init/CliRunner.test.ts
test/unit/ldp/http/BasicResponseWriter.test.ts
test/unit/ldp/http/metadata/BasicMetadataExtractor.test.ts
test/unit/logging/LogUtil.test.ts
test/unit/server/ExpressHttpServer.test.ts
test/unit/storage/LockingResourceStore.test.ts
test/unit/storage/SingleThreadedResourceLocker.test.ts
test/unit/storage/accessors/FileDataAccessor.test.ts
test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts
test/util/TestHelpers.ts

To anticipate https://github.com/solid/community-server/pull/289#pullrequestreview-520844502 in the future.

Use Jest recommended linting

---

package-lock.json
package.json

Closes https://github.com/solid/community-server/issues/308

Update dependency n3 to v1.6.4

---

package.json

chore: Split pre-commit unit and integration tests

---

src/storage/MonitoringStore.ts
test/unit/storage/MonitoringStore.test.ts

As a preparation for adding features like WebSockets.

feat: Add a monitoring store

---

.eslintrc.js
src/ldp/UnsecureWebSocketsProtocol.ts
test/unit/ldp/UnsecureWebSocketsProtocol.test.ts

Implements https://github.com/solid/solid-spec/blob/master/api-websockets.md
Depends on #336.

Add the legacy Solid WebSocket protocol

---

src/storage/mapping/ExtensionBasedMapper.ts

docs: add warning to ExtensionBasedMapper regarding performance

---

src/authorization/AclManager.ts
src/authorization/UrlBasedAclManager.ts
src/authorization/WebAclAuthorizer.ts
src/init/Setup.ts
test/unit/authorization/UrlBasedAclManager.test.ts
test/unit/authorization/WebAclAuthorizer.test.ts
test/unit/init/Setup.test.ts

fix: Correctly handle acl behaviour for acl identifiers

---

config/config-default.json
config/config-file.json
config/config-path-routing.json
config/config-rdf-to-sparql-endpoint.json
config/config-sparql-endpoint.json
config/presets/acl.json
config/presets/http.json
config/presets/ldp/operation-handler.json
config/presets/ldp/response-writer.json
config/presets/ldp/websockets.json
config/presets/setup.json
config/presets/storage-wrapper.json
index.ts
package-lock.json
package.json
src/ldp/http/metadata/WebSocketMetadataWriter.ts
test/unit/ldp/http/metadata/WebSocketMetadataWriter.test.ts

Wire up the legacy WebSocket protocol

---

config/presets/storage/backend/storage-sparql-endpoint.json

fix: Update quad converter config parameters

---

src/storage/patch/SparqlUpdatePatchHandler.ts
test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts

fix: Always release lock when patching

---

src/storage/DataAccessorBasedStore.ts
test/unit/storage/DataAccessorBasedStore.test.ts

fix: Create container data before adding content-type

---

src/init/Setup.ts
test/unit/init/Setup.test.ts

Fixes https://github.com/solid/community-server/issues/382

Do not overwrite existing root ACL

---

src/storage/accessors/SparqlDataAccessor.ts
test/unit/storage/accessors/SparqlDataAccessor.test.ts

Closes #349 (again (hopefully))

fix: Only set content-type for documents in sparql store

---

src/storage/patch/SparqlUpdatePatchHandler.ts
test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts

Was going through the Solid spec and noticed PATCH is supposed to do this.

feat: Create new resources when patching

---

index.ts
src/storage/ReadOnlyStore.ts
test/unit/storage/ReadOnlyStore.test.ts

Closes https://github.com/solid/community-server/issues/193
Closes https://github.com/solid/community-server/issues/323

Add read-only store

---

src/init/AclInitializer.ts
src/ldp/representation/RepresentationMetadata.ts
src/ldp/representation/ResourceIdentifier.ts
src/pods/generate/TemplatedResourcesGenerator.ts
src/storage/DataAccessorBasedStore.ts
src/storage/accessors/FileDataAccessor.ts
src/storage/accessors/InMemoryDataAccessor.ts
src/storage/accessors/SparqlDataAccessor.ts
src/storage/patch/SparqlUpdatePatchHandler.ts
test/unit/ldp/representation/RepresentationMetadata.test.ts
test/unit/storage/accessors/FileDataAccessor.test.ts
test/unit/storage/accessors/InMemoryDataAccessor.test.ts
test/unit/storage/accessors/SparqlDataAccessor.test.ts

Closes https://github.com/solid/community-server/issues/388

Make RepresentationMetadata accept a ResourceIdentifier

---

src/authentication/UnsecureConstantCredentialsExtractor.ts
test/unit/authentication/UnsecureConstantCredentialsExtractor.test.ts

Closes https://github.com/solid/community-server/issues/397

Add constant WebID extractor

---

src/storage/DataAccessorBasedStore.ts
src/storage/accessors/FileDataAccessor.ts
src/storage/mapping/ExtensionBasedMapper.ts
src/storage/mapping/FileIdentifierMapper.ts
src/util/QuadUtil.ts
test/unit/storage/accessors/FileDataAccessor.test.ts
test/unit/storage/mapping/ExtensionBasedMapper.test.ts
test/unit/util/QuadUtil.test.ts

Closes #341 
It does not solve the last of the three comments there but I'm not really sure if that is needed. In both cases a converter would be required so changing it from turtle to quads should not make much of a difference.

Remove metadata content-type assumptions

---

.github/workflows/ci.yml
.gitignore
README.md
package-lock.json
package.json
typedoc.json

Closes https://github.com/solid/community-server/issues/434

Add TypeDoc

---

config/presets/representation-conversion.json
src/storage/conversion/QuadToRdfConverter.ts
test/unit/storage/conversion/QuadToRdfConverter.test.ts

Fixes https://github.com/solid/community-server/issues/463

Prefer Turtle as default content type

---

.eslintrc.js
package-lock.json
package.json
src/ldp/representation/RepresentationMetadata.ts
src/storage/conversion/QuadToRdfConverter.ts
src/util/TermUtil.ts
src/util/Vocabularies.ts
test/integration/LpdHandlerOperations.test.ts
test/unit/ldp/representation/RepresentationMetadata.test.ts
test/unit/storage/conversion/QuadToRdfConverter.test.ts
test/unit/util/Vocabularies.test.ts

Closes https://github.com/solid/community-server/issues/470
Can't do it directly with the main serializer because of https://github.com/rubensworks/rdf-serialize.js/issues/1

Support writer prefixes

---

src/storage/DataAccessorBasedStore.ts
test/unit/storage/DataAccessorBasedStore.test.ts

fix: Prevent POST requests from creating intermediate containers

---

config/presets/representation-conversion.json
src/index.ts
src/storage/conversion/ContentTypeReplacer.ts
test/unit/storage/conversion/ContentTypeReplacer.test.ts
test/unit/storage/conversion/RdfToQuadConverter.test.ts

I figured that no actual conversion is needed when going from N-Triples to Turtle, Turtle to TriG, etc.

Only convert representations when needed

---

src/authorization/WebAclAuthorizer.ts
test/unit/authorization/WebAclAuthorizer.test.ts

fix: Update acl authorizer to make write rights imply append rights

---

src/util/StreamUtil.ts
test/unit/util/StreamUtil.test.ts

Makes it easier for component implementers to keep streams safe (https://github.com/solid/community-server/issues/489).
The `transformSafely` function:
- catches errors on the source
- synchronous and asynchronous errors on transform
- synchronous and asynchronous errors on flush
Example usage:
- https://github.com/RubenVerborgh/solid-hue/commit/6221b9a56ab81c368cb53672e87a0e682dd1b6bf#diff-7f00ccca0a5d684cf6667c08205326e57b649644720382cc86c92276fdf0dca4R29-R45
- https://github.com/RubenVerborgh/solid-hue/commit/6221b9a56ab81c368cb53672e87a0e682dd1b6bf#diff-31541e15402fa0d5b58a80acc368dac7894e6f9fa9a1cbba2950eedfaa99c4b1R22-R45

Add transformSafely

---

.gitignore
package.json

This seems like a useful convenience script, if anything to provide a relatively easily accessible sane default for persistant data and hint at the possibility of using bundled alternative configurations.

feat: Start server using filestorage

---

src/ldp/http/RawBodyParser.ts
test/integration/ServerWithAuth.test.ts
test/unit/ldp/http/RawBodyParser.test.ts

Fixes https://github.com/solid/community-server/issues/498

Allow Content-Type: 0 on GET

---

src/ldp/UnsecureWebSocketsProtocol.ts
test/integration/WebSocketsProtocol.test.ts
test/unit/ldp/UnsecureWebSocketsProtocol.test.ts

See https://github.com/solid/solid-spec/pull/230

Use solid-0.1 as protocol string

---

src/init/CliRunner.ts
src/util/PathUtil.ts
test/integration/Config.ts
test/unit/init/CliRunner.test.ts
test/unit/util/PathUtil.test.ts

refactor: Remove toSystemFilePath

---

src/ldp/permissions/SparqlPatchPermissionsExtractor.ts
src/storage/patch/SparqlUpdatePatchHandler.ts
test/integration/LpdHandlerOperations.test.ts
test/unit/ldp/permissions/SparqlPatchPermissionsExtractor.test.ts
test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts

feat: Support composite PATCH updates

---

config/config-default.json
config/config-file.json
config/config-path-routing.json
config/config-rdf-to-sparql-endpoint.json
config/config-sparql-endpoint.json
config/presets/http.json
config/presets/representation-conversion.json
config/presets/static.json
src/index.ts
src/server/middleware/StaticAssetHandler.ts
test/integration/config/ldp-with-auth.json
test/integration/config/server-middleware.json
test/integration/config/server-without-auth.json
test/unit/server/middleware/StaticAssetHandler.test.ts

Allows serving CSS, JS, etc. for https://github.com/solid/community-server/issues/510

Add StaticAssetHandler

---

config/presets/ldp/response-writer.json
config/presets/middleware.json
src/index.ts
src/ldp/http/metadata/ConstantMetadataWriter.ts
src/ldp/http/metadata/LinkRelMetadataWriter.ts
src/ldp/http/metadata/MappedMetadataWriter.ts
src/server/middleware/WebSocketAdvertiser.ts
test/integration/LdpHandlerWithoutAuth.test.ts
test/integration/Middleware.test.ts
test/unit/ldp/http/metadata/ConstantMetadataWriter.test.ts

Closes https://github.com/solid/community-server/issues/539

Add MS-Author-Via header

---

config/presets/ldp/response-writer.json
src/index.ts
src/ldp/http/metadata/AclLinkMetadataWriter.ts
test/integration/LdpHandlerWithAuth.test.ts
test/integration/LdpHandlerWithoutAuth.test.ts
test/integration/LpdHandlerOperations.test.ts
test/integration/config/server-without-auth.json
test/unit/ldp/http/metadata/AclLinkMetadataWriter.test.ts

Closes #538 .
Chances are this will be replaced by a more generic solution in the future.

Add acl link header writer

---

src/ldp/permissions/MethodPermissionsExtractor.ts
test/integration/LdpHandlerWithAuth.test.ts
test/unit/ldp/permissions/MethodPermissionsExtractor.test.ts

fix: Only require append permissions on POST requests

---

package-lock.json
package.json
src/server/middleware/StaticAssetHandler.ts
test/unit/server/middleware/StaticAssetHandler.test.ts

Closes https://github.com/solid/community-server/issues/548

Support folders in StaticAssetHandler

---

test/unit/ldp/http/metadata/SlugParser.test.ts
test/unit/ldp/permissions/SparqlPatchPermissionsExtractor.test.ts
test/unit/logging/LazyLogger.test.ts
test/unit/logging/LazyLoggerFactory.test.ts
test/unit/logging/LogUtil.test.ts
test/unit/storage/DataAccessorBasedStore.test.ts
test/unit/storage/LockingResourceStore.test.ts
test/unit/storage/RoutingResourceStore.test.ts
test/unit/storage/accessors/FileDataAccessor.test.ts
test/unit/storage/accessors/InMemoryDataAccessor.test.ts
test/unit/storage/accessors/SparqlDataAccessor.test.ts
test/unit/storage/conversion/ContentTypeReplacer.test.ts
test/unit/storage/conversion/ConversionUtil.test.ts
test/unit/storage/mapping/BaseFileIdentifierMapper.test.ts
test/unit/storage/mapping/ExtensionBasedMapper.test.ts
test/unit/storage/mapping/FixedContentTypeMapper.test.ts
test/unit/storage/routing/RegexRouterRule.test.ts
test/unit/util/StreamUtil.test.ts

Closes #371.
There were several cases where we were testing for the wrong error classes because of this.

fix: Test error classes correctly

---

src/util/StreamUtil.ts
test/unit/util/StreamUtil.test.ts

fix: Close unpiped streams

---

config/presets/middleware.json
src/server/middleware/CorsHandler.ts
test/integration/Middleware.test.ts

fix: Prevent race condition in OPTIONS call

---

src/ldp/http/SparqlUpdateBodyParser.ts

Closes #589 .
No idea why the integration tests didn't catch this. Maybe because of the mocking library?

fix: Fix problem with piping streams for PATCH requests

---

package-lock.json
package.json
src/server/middleware/CorsHandler.ts

refactor: upgraded @types/cors

---

package-lock.json
package.json
src/storage/patch/SparqlUpdatePatchHandler.ts
test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts

Fixes https://github.com/solid/community-server/issues/626

fix: SPARQL algebra update

---

package-lock.json
package.json

Fixes https://github.com/solid/conformance-test-harness/issues/1

fix: Update faulty token verifier

---

config/presets/identity/solid-identity-provider.json
src/identity/interaction/util/BasicIssuerReferenceWebIdOwnershipValidator.ts
src/identity/storage/ClientWebIdFetchingStorageAdapterFactory.ts
src/index.ts
src/util/Vocabularies.ts

Support for clientids in the tokens

Client Id Support

---

src/identity/interaction/email-password/handler/EmailPasswordForgotPasswordHandler.ts
src/identity/interaction/email-password/handler/EmailPasswordGetResetPasswordHandler.ts
src/identity/interaction/email-password/handler/EmailPasswordLoginHandler.ts
src/identity/interaction/email-password/handler/EmailPasswordRegistrationHandler.ts
src/identity/interaction/email-password/handler/EmailPasswordResetPasswordHandler.ts
src/identity/interaction/email-password/storage/EmailPasswordStore.ts
src/identity/interaction/util/FormDataUtil.ts
src/identity/interaction/util/IdpRenderHandler.ts
src/util/ContentTypes.ts
test/unit/identity/interaction/email-password/handler/EmailPasswordForgotPasswordHandler.test.ts
test/unit/identity/interaction/email-password/handler/EmailPasswordGetResetPasswordHandler.test.ts
test/unit/identity/interaction/email-password/handler/EmailPasswordLoginHandler.test.ts
test/unit/identity/interaction/email-password/handler/EmailPasswordRegistrationHandler.test.ts
test/unit/identity/interaction/email-password/handler/EmailPasswordResetPasswordHandler.test.ts
test/unit/identity/interaction/email-password/handler/EmailPasswordResetPasswordRenderHandler.test.ts
test/unit/identity/interaction/email-password/handler/Util.ts

And some minor refactors here and there

Add unit tests for all email-password handlers

---

config/presets/identity/email-password-interaction-policy.json
src/identity/interaction/util/BasicIssuerReferenceWebIdOwnershipValidator.ts
src/identity/interaction/util/ChooseInitialInteractionHandler.ts
src/identity/interaction/util/EjsTemplateRenderer.ts
src/identity/interaction/util/EmailSender.ts
src/identity/interaction/util/IdpRouteController.ts
src/identity/storage/ClientWebIdFetchingStorageAdapterFactory.ts
src/identity/util/FetchUtil.ts
test/unit/identity/FetchUtil.test.ts
test/unit/identity/interaction/IdpInteractionHttpHandler.test.ts
test/unit/identity/interaction/email-password/EmailPasswordInteractionPolicy.test.ts
test/unit/identity/interaction/util/BasicIssuerReferenceWebIdOwnershipValidator.test.ts
test/unit/identity/interaction/util/ChooseInitialInteractionHandler.test.ts
test/unit/identity/interaction/util/EjsTemplateRenderer.test.ts
test/unit/identity/interaction/util/EmailSender.test.ts
test/unit/identity/interaction/util/FormDataUtil.test.ts
test/unit/identity/interaction/util/IdpRouteController.test.ts
test/unit/identity/interaction/util/OidcInteractionCompleter.test.ts
test/unit/identity/storage/ClientWebIdFetchingStorageAdapterFactory.test.ts

Getting closer to that 100%.
This also fixes the warning that was given when starting the server.
The integration test still works with these changes so at least nothing major breaks.

More Idp unit tests and refactors

---

test/unit/init/CliRunner.test.ts

Small fix. This was bothering me.
Also added a separate unit test for testing the case of default input parameters.

fix: Prevent CliRunner tests from outputting errors

---

package-lock.json
src/identity/IdentityProviderHttpHandler.ts
src/identity/configuration/KeyGeneratingIdpConfigurationGenerator.ts
src/identity/interaction/IdpSessionHttpHandler.ts
src/identity/interaction/email-password/EmailPasswordInteractionPolicy.ts
src/identity/interaction/email-password/EmailPasswordUtil.ts
src/identity/interaction/email-password/handler/EmailPasswordForgotPasswordHandler.ts
src/identity/interaction/email-password/handler/EmailPasswordLoginHandler.ts
src/identity/interaction/email-password/handler/EmailPasswordRegistrationHandler.ts
src/identity/interaction/email-password/handler/EmailPasswordResetPasswordHandler.ts
src/identity/interaction/util/BasicIssuerReferenceWebIdOwnershipValidator.ts
src/identity/interaction/util/ChooseInitialInteractionHandler.ts
src/identity/interaction/util/OidcInteractionCompleter.ts
src/identity/storage/ClientWebIdFetchingStorageAdapterFactory.ts
src/identity/storage/ExpiringStorageAdapterFactory.ts
src/server/BaseHttpServerFactory.ts

Should make it easier to debug if there are issues.

feat: Add more logging

---

src/util/identifiers/BaseIdentifierStrategy.ts
test/unit/util/identifiers/BaseIdentifierStrategy.test.ts

In order to make issues such as #703 easier to understand.

Improve identifier error messages

---

package-lock.json
package.json

Fix https://github.com/solid/identity-token-verifier/issues/6

chore: update identity token verifier

---

config/presets/http.json
templates/views/email-password-interaction/confirm.ejs
templates/views/email-password-interaction/emailSent.ejs
templates/views/email-password-interaction/error.ejs
templates/views/email-password-interaction/forgotPassword.ejs
templates/views/email-password-interaction/login.ejs
templates/views/email-password-interaction/message.ejs
templates/views/email-password-interaction/register.ejs
templates/views/email-password-interaction/resetPassword.ejs
templates/views/email-password-interaction/resetPasswordEmailTemplate.ejs

Closes #689 .
Will require some changes to solve #691 but not that relevant right now.

refactor: Link css instead of injecting

---

.github/workflows/ci.yml

Makes sure tests stop if something goes wrong.

test: Time out CI jobs after 10 minutes

---

bin/server.js
src/index.ts
src/init/AppRunner.ts
src/init/CliRunner.ts
test/unit/init/AppRunner.test.ts

Just a tiny change that allows the server to be started from another JS app, instead of just from the CLI.

feat: make methods in CliRunner public

---

src/authorization/WebAclAuthorizer.ts

I happened to be skimming the file, and thought this would make it more intuitive.

Document WebACL algorithm more

---

Dockerfile
README.md
documentation/Create-a-custom-configuration.md
documentation/Notes-for-developers.md

Hi!
This is my first PR here... I just updated some documentation files (+ the dockerfile) with the new paths for the config files (as a follow up to #732).
I hope everything is OK.
Simone

fix: Update config files path

---

config/util/index/example.json
src/storage/conversion/ConstantConverter.ts
test/unit/storage/conversion/ConstantConverter.test.ts

fix: Add conditional parameters to ConstantConverter

---

.eslintrc.js
config/ldp/metadata-writer/default.json
config/ldp/metadata-writer/writers/www-auth.json
src/index.ts
src/ldp/http/metadata/WwwAuthMetadataWriter.ts
test/integration/LdpHandlerWithAuth.test.ts
test/unit/ldp/http/metadata/WacAllowMetadataWriter.test.ts
test/unit/ldp/http/metadata/WwwAuthMetadataWriter.test.ts

feat: Create WWW-Authenticate metadata writer

---

package-lock.json
package.json
src/ldp/permissions/SparqlPatchPermissionsExtractor.ts
src/storage/patch/SparqlUpdatePatchHandler.ts
test/unit/ldp/permissions/SparqlPatchPermissionsExtractor.test.ts
test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts

fix: Support empty PATCH requests

---

config/util/representation-conversion/default.json
src/index.ts
src/storage/conversion/ErrorToTemplateConverter.ts
src/util/ContentTypes.ts
templates/error/error.hbs
test/unit/storage/conversion/ErrorToTemplateConverter.test.ts

Closes #654.
Will also have to change after #721 is resolved.

feat: Add ErrorToHtmlConverter using templates

---

README.md

Realized I forgot to update this with the last PR

docs: Update IDP registration README

---

src/index.ts
src/storage/patch/ConvertingPatchHandler.ts
src/storage/patch/SparqlUpdatePatchHandler.ts
test/unit/storage/patch/ConvertingPatchHandlers.test.ts
test/unit/storage/patch/SparqlUpdatePatchHandler.test.ts

feat: Create base ConvertingPatchHandler abstract class

---

src/storage/conversion/ChainedConverter.ts
test/unit/storage/conversion/ChainedConverter.test.ts

I discovered that the initial assumption that the shortest path is always going to be good enough was wrong. Specifically I was looking into outputting HTML for errors by going Error -> Markdown -> HTML. Since the ChainedConverter always prioritizes finding the shortest path, this caused Markdown to be returned instead of html since my browser had an accept header of `Accept: text/html, */*;q=0.8`, which reduces the amount of interesting things we can do with the ChainedConverter.
This fix makes sure the best path always gets returned. Since this increases the complexity I added some basic pruning in there, but it should still not be that big of a deal since we don't have that many converters and most of them can't be chained to eachother.

fix: Always find the best path with ChainedConverter

---

test/integration/LdpHandlerWithAuth.test.ts

Adds test that closes #537 .
The second test fails without the change done in the authorizer. Currently in draft because I'm actually not sure if this is something that requires fixing, depends on URL interpretation. The case is that if the server receives `/&foo` as an url it's going to convert it to `/%26foo` which means it won't match with an acl file referencing `/&foo`. This change fixes that, although I would add a `toCanonicalUrl` function to pathUtil if this fix is needed. But we could also say that we require acl files to have normalized URLs. We could even add a validator for that at some point.

Add tests for acl edge cases

---

jest.config.js

Fixes https://github.com/solid/community-server/issues/801

fix: Tests timeout on slower machines

---

src/authorization/WebAclAuthorizer.ts
src/init/AclInitializer.ts
test/unit/authorization/WebAclAuthorizer.test.ts
test/unit/init/AclInitializer.test.ts

Closes #808 (if that was the problem)

Return 500 in case of invalid acl

---

config/identity/handler/provider-factory/identity.json
src/identity/configuration/IdentityProviderFactory.ts
test/unit/identity/configuration/IdentityProviderFactory.test.ts

This does not fix the client_id issue, but since I'm not sure when that fix is going to be finished I'm already pushing this part.

fix: Add necessary claims to access and id tokens

---

config/http/static/default.json
src/init/AppRunner.ts

Nothing major, I was just confused by the presence of both `getApp` and `createApp`, so I merged them and reordered things a bit.

Simplify AppRunner methods

---

config/http/static/default.json
src/server/middleware/StaticAssetHandler.ts
test/unit/server/middleware/StaticAssetHandler.test.ts

Closes https://github.com/solid/community-server/issues/861

Cache static assets

---

config/http/middleware/handlers/cors.json
test/integration/Middleware.test.ts

Closes https://github.com/solid/community-server/issues/873

fix: Expose WAC-Allow via CORS

---

src/util/StreamUtil.ts
test/integration/GuardedStream.test.ts
test/unit/util/StreamUtil.test.ts

Closes #842.
Not exactly the most stable solution but it does solve the problem.

fix: Prevent warnings for expected errors

---

src/identity/interaction/email-password/EmailPasswordUtil.ts
src/identity/interaction/email-password/handler/RegistrationHandler.ts
templates/identity/email-password/login.html.ejs
templates/identity/email-password/register-response.html.ejs
templates/identity/email-password/register.html.ejs
templates/styles/main.css
test/integration/Identity.test.ts
test/unit/identity/interaction/email-password/EmailPasswordUtil.test.ts
test/unit/identity/interaction/email-password/handler/RegistrationHandler.test.ts
test/unit/identity/interaction/email-password/handler/ResetPasswordHandler.test.ts

This is a redesign for the registration form so it is easier to understand what the different options are and how they interact.

Make registration form self-explanatory

---

package-lock.json
package.json
src/util/ContentTypes.ts

Just a minor follow-up for #773.

chore: bump mime-types with support for TriG

---

README.md
config/app/init/initializers/root.json
config/http/static/default.json
config/identity/handler/default.json
config/identity/handler/interaction/routes/forgot-password.json
config/identity/handler/interaction/routes/login.json
config/identity/handler/interaction/routes/reset-password.json
config/identity/handler/interaction/routes/session.json
config/identity/pod/resource-generators/templated.json
config/identity/registration/route/registration.json
config/util/representation-conversion/converters/markdown.json
src/init/AppRunner.ts
src/pods/generate/TemplatedResourcesGenerator.ts
src/server/middleware/StaticAssetHandler.ts
src/storage/conversion/ErrorToTemplateConverter.ts
src/util/PathUtil.ts
test/unit/init/AppRunner.test.ts
test/unit/server/middleware/StaticAssetHandler.test.ts
test/unit/storage/conversion/ErrorToTemplateConverter.test.ts
test/unit/util/PathUtil.test.ts

This PR enables
```shell
community-solid-server -c @css:config/file.json
```

Make it easier to start the server with a built-in config file

---

src/identity/IdentityProviderHttpHandler.ts
templates/identity/email-password/register-response.html.ejs
test/unit/identity/IdentityProviderHttpHandler.test.ts

Part of #880, closes #853 (sort of)

Only link to log in page while in an auth flow

---

src/identity/interaction/SessionHttpHandler.ts
templates/identity/email-password/confirm.html.ejs
templates/identity/email-password/forgot-password.html.ejs
templates/identity/email-password/login.html.ejs
templates/identity/email-password/reset-password.html.ejs
test/integration/Identity.test.ts
test/unit/identity/interaction/SessionHttpHandler.test.ts

fix: Allow clients to be remembered in the SessionHttpHandler

---

config/storage/backend/regex.json

fix: Convert data to SparqlDataAccessor in regex config

---

src/storage/conversion/ConstantConverter.ts
test/unit/storage/conversion/ConstantConverter.test.ts

feat: Allow filtering in ConstantConverter based on type

---

CHANGELOG.md
README.md
RELEASE_NOTES.md
config/storage/backend/regex.json
package-lock.json
package.json
src/storage/conversion/ConstantConverter.ts
test/unit/storage/conversion/ConstantConverter.test.ts

Add 1.1.0 changes to 2.0.0 branch

Merge 1.1.0 into 2.0.0

---

src/storage/DataAccessorBasedStore.ts
test/unit/storage/DataAccessorBasedStore.test.ts

Discovered a bug in the 2.0.0 branch where generated metadata got written to containers when updating their timestamp after the membership triples changed.

fix: Prevent parent containers from storing generated metadata

---

package-lock.json
package.json

chore(deps): Update access-token-verifier

---

config/ldp/authorization/readers/ownership.json
config/ldp/authorization/webacl.json
src/authorization/OwnerPermissionReader.ts
src/identity/interaction/email-password/handler/LoginHandler.ts
src/identity/interaction/email-password/storage/AccountStore.ts
src/identity/interaction/email-password/storage/BaseAccountStore.ts
src/identity/interaction/email-password/util/RegistrationManager.ts
src/index.ts
templates/identity/email-password/register-partial.html.ejs
test/integration/DynamicPods.test.ts
test/integration/Identity.test.ts
test/integration/Subdomains.test.ts
test/integration/config/ldp-with-auth.json
test/unit/authorization/OwnerPermissionReader.test.ts
test/unit/identity/interaction/email-password/handler/LoginHandler.test.ts
test/unit/identity/interaction/email-password/storage/BaseAccountStore.test.ts
test/unit/identity/interaction/email-password/util/RegistrationManager.test.ts

Closes #720 
Depends on #936 
Some issues with this solution, some of them caused by architecture that might have to change:
1. Several components need things from the AccountStore but use a different key to access it. The login handler uses the email address while this new authorizer uses the WebID. This has been solved by allowing settings to be accessed through the WebID but an ideal solution would be to have a storage that can be queried (a triple store for example). But adding that while using the ResourceStore as backend and keeping it efficient is not going to be easy/possible.
2. The WAC-Allow headers are not going to be correct (or present event) for request that get handled by this authorizer. That is because a) this authorizer doesn't check the other permissions and b) this …

Always give the pod owner control access

---

config/ldp/handler/components/error-handler.json
config/storage/middleware/stores/converting.json
config/util/representation-conversion/default.json

Fixes https://github.com/solid/community-server/issues/1034

Do not serve UI on special pages

---

src/util/PromiseUtil.ts

Took me a while to understand the infinite promise 🙂

refactor: Simplify promiseSome

---

src/authentication/BearerWebIdExtractor.ts
src/authentication/DPoPWebIdExtractor.ts
src/authentication/UnsecureWebIdExtractor.ts
test/unit/authentication/BearerWebIdExtractor.test.ts
test/unit/authentication/DPoPWebIdExtractor.test.ts
test/unit/authentication/UnsecureWebIdExtractor.test.ts

As per https://github.com/solid/access-token-verifier/issues/17#issuecomment-985407893

Accept lowercase Authorization tokens

---

.github/PULL_REQUEST_TEMPLATE.md

Fixes #1089
Adds a more strict pull request template to this repo

Made pull request template more strict

---

RELEASE_NOTES.md

docs: Update release notes with official docker image publishing.

---

package-lock.json
package.json
test/integration/Identity.test.ts
test/integration/IdentityTestState.ts

#838
Adds an integration test for clients that have a valid WebID when authenticating with the IDP.

test: Add IDP integration test for clients with a WebID

---

README.md

#1051
This PR just adds a line to the README, referencing the Helm Chart on ArtifactHUB for Kubernetes deployment.

docs: Close #1051 by adding a reference to the Helm Chart in the README.

---

.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
guides/custom-configurations.md
guides/developer-notes.md
package.json
src/http/ldp/PatchOperationHandler.ts
src/http/ldp/PutOperationHandler.ts
src/identity/configuration/IdentityProviderFactory.ts
src/storage/LockingResourceStore.ts
src/storage/accessors/ValidatingDataAccessor.ts
src/storage/conversion/ChainedConverter.ts
src/util/GuardedStream.ts
templates/error/descriptions/H401.md.hbs
templates/error/descriptions/H500.md.hbs
templates/error/descriptions/H501.md.hbs
templates/root/prefilled/index.html
templates/setup/input-partial.html.ejs
test/integration/LdpHandlerWithoutAuth.test.ts
test/unit/http/input/body/RawBodyParser.test.ts

#1216
I think I got all of them. These are the things that did not yet get updated:
* gitter link (waiting on the move)
* package.json name, links to npm package, components.js context URLs (as these are all tied together)

chore: Update links for new repository

---

src/storage/accessors/FileDataAccessor.ts
src/util/HeaderUtil.ts
src/util/Vocabularies.ts
test/unit/http/auxiliary/RdfValidator.test.ts
test/unit/http/input/BasicRequestParser.test.ts
test/unit/storage/accessors/FileDataAccessor.test.ts
test/unit/storage/accessors/SparqlDataAccessor.test.ts
test/unit/util/HeaderUtil.test.ts
test/unit/util/ResourceUtil.test.ts

Closes #1207 
No breaking changes so can go directly into main.

fix: Add IANA type to child metadata in FileDataAccessor

---

documentation/seeding-pods.md
test/integration/SeedingPods.test.ts
test/util/Util.ts

We didn't have an integration test for this yet. Lowers the chances of accidentally breaking this feature in the future.

test: Add pod seeding integration test

---

.github/workflows/schedule.yml
package-lock.json
test/deploy/conformance.env
test/deploy/createAccountCredentials.ts
test/deploy/tsconfig.json

Removes need for #1218. Depends on #1258.
Main question is how to best integrate this in the repository. This is one suggestion on how to do it but perhaps makes it a bit weird with the separate tsconfig and build.
Succesful run on test branch: https://github.com/CommunitySolidServer/CommunitySolidServer/runs/5971460890?check_suite_focus=true#step:11:62

Update CTH run to use client credentials

---

src/util/PathUtil.ts
test/integration/FileBackendEncodedSlashHandling.test.ts
test/unit/util/PathUtil.test.ts

…that was a wild ride. Observation and solution path via @bourgeoa.

Make delimiter encoding case-insensitive

---

CHANGELOG.md

Refactoring the Changelog on the versions branch to negate potential merge issues

refactor: conventional-changelog format

---

Dockerfile

* #1357 
This PR streamlines the Dockerfile a bit:
* Removed unnecessary package.json copy
* Changed build image to alpine version too
* Changed maintainer.

perf: small improvement to dockerfile building and switching maintainer

---

src/http/output/BasicResponseWriter.ts
src/server/BaseHttpServerFactory.ts
test/unit/server/BaseHttpServerFactory.test.ts

Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1243
Half the time was probably spent figuring out how to cover that line in the unit test.

fix: Improve HTTP stream error messages

---

.github/workflows/ci.yml

Small fix for the docker tests. (the cannot pull the image from docker hub when it is locally not available and should fail then)

ci: docker test fixes

---

documentation/markdown/seeding-pods.md

None, afaik.
Inrupt PodSpaces has been migrated to ESS 2.0 and the URLs have all changed. This change updates the documentation to reference the new URLs. https://inrupt.com/blog/pod-spaces-upgrade
I'm not sure what the other steps are there or if they apply.

docs: updating seeding pods to reference new URLs

---

RELEASE_NOTES.md
config/ldp/authorization/readers/access-checkers/agent-group.json
src/authorization/access/AgentGroupAccessChecker.ts
test/unit/authorization/access/AgentGroupAccessChecker.test.ts

#1331 
Cache removed from AgentGroupAccesChecker, fairly straightforward.

feat!: remove caching from AgentGroupAccessChecker

---

documentation/markdown/usage/metadata.md

fix: update metadata documentation

---

templates/identity/email-password/consent.html.ejs
templates/scripts/util.js
templates/styles/main.css

The authorization screen currently looks like this:
However, I expect the default button to be on the right.
This PR changes this, and I got a little carried away.
Is there an easy way to test this?

Put default consent button in expected position

---

config/http/middleware/handlers/cors.json
test/integration/Middleware.test.ts

Closes #1502.
Doing the same thing as #874.
---
I'm a first time contributor. Happy to improve this PR if someone guides me.

Expose Www-Authenticate via CORS

---

.github/workflows/cth-test.yml
.github/workflows/docker.yml
.github/workflows/mkdocs.yml
.github/workflows/npm-test.yml
.github/workflows/stale.yml
.github/workflows/typedocs.yml
CHANGELOG.md
RELEASE_NOTES.md
config/http/middleware/handlers/cors.json
config/ldp/modes/default.json
config/sparql-file-storage.json
config/util/auxiliary/no-acl.json
package-lock.json
package.json
src/authorization/permissions/CreateModesExtractor.ts
src/authorization/permissions/DeleteParentExtractor.ts
src/index.ts
src/util/locking/RedisLocker.ts
test/integration/Middleware.test.ts
test/integration/PermissionTable.test.ts
test/integration/Quota.test.ts
test/unit/authorization/permissions/CreateModesExtractor.test.ts
test/unit/authorization/permissions/DeleteParentExtractor.test.ts
test/unit/util/locking/RedisLocker.test.ts

Merge main into v6.0.0 branch

---

.github/workflows/docker.yml

#1546 
Included `linux/arm/v8` platform in Docker builds.

#1546 - Add linux/arm/v8

---

config/http/notifications/webhooks/handler.json
config/http/notifications/webhooks/routes.json
config/http/notifications/webhooks/subscription.json
documentation/markdown/usage/notifications.md
src/server/description/StorageDescriptionHandler.ts
src/server/notifications/WebHookChannel2023/WebhookChannel2023Type.ts
src/util/Vocabularies.ts
test/integration/WebHookChannel2023.test.ts
test/integration/WebSocketChannel2023.test.ts
test/unit/server/description/StorageDescriptionHandler.test.ts
test/unit/server/notifications/WebHookChannel2023/WebHookChannel2023Type.test.ts
test/unit/server/notifications/WebHookChannel2023/WebHookEmitter.test.ts
test/util/NotificationUtil.ts

Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1641 and closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1656 .
Use the correct subject in the storage description resource and use Webhook instead of WebHook. The Webhook classes have not been renamed because that would be a breaking change. See https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1658

Fix minor issues related to notifications

---

config/util/representation-conversion/converters/rdf-to-quad.json
templates/contexts/activitystreams.jsonld

Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1673
Prevents the server from doing a call to the context every time it has to convert notification JSON-LD.

fix: Store activity streams context locally

---

src/util/HeaderUtil.ts
test/unit/util/HeaderUtil.test.ts

Continuation of https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1103 on different branch to avoid issues.
Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/469
See linked PR for discussion. Finished up the PR here and added support for still enabling strict mode when required.

Ignore invalid header parts

---

README.md
documentation/markdown/README.md
documentation/markdown/usage/starting-server.md

The three commits incrementally enhance the documentation, can be cut off at any point.

Clarify README, highlight ease of quickly starting a server

---

RELEASE_NOTES.md
config/app/README.md
config/app/init/initialize-root-pod.json
config/app/init/initializers/root-pod.json
config/file-root-pod.json
src/identity/AccountInitializer.ts
src/index.ts
templates/pod/base/README$.md.hbs
test/unit/identity/AccountInitializer.test.ts

Setup was removed in https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1677 which also removed the option to create a root pod. This re-introduces it as a config option.

Add support for root pods

---

Dockerfile

Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1761

chore: Fix Dockerfile to Node v18 to prevent build issues

---

documentation/markdown/architecture/features/protocol/overview.md
documentation/markdown/architecture/features/protocol/patching.md
documentation/mkdocs.yml

Added architecture documentation for the components responsible for applying a PATCH request.

docs: Explain the patching store in-depth

---

templates/identity/account/create-client-credentials.html.ejs
templates/identity/account/create-pod.html.ejs
templates/identity/account/link-webid.html.ejs
templates/identity/account/pod-settings.html.ejs
templates/identity/login.html.ejs
templates/identity/oidc/consent.html.ejs
templates/identity/password/create.html.ejs
templates/identity/password/forgot.html.ejs
templates/identity/password/login.html.ejs
templates/identity/password/register.html.ejs
templates/identity/password/reset.html.ejs
templates/identity/password/update.html.ejs
templates/scripts/util.js
templates/styles/main.css

Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1768
Disables all submit buttons until a listener is attached to the form

fix: Disable submit buttons until form data is loaded

---

documentation/markdown/usage/identity-provider.md

Noticed this documentation had some outdated parts.

docs: Fix outdated information in IDP documentation

---

config/storage/README.md
src/http/output/metadata/StorageDescriptionAdvertiser.ts

Discovered that the explanation for this import option was missing.
Added some more explanation for the related error that could be logged.

docs: Explain storage/location import options

---

templates/main.html.ejs

https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1776
A quick fix to prevent the issue of people having problems with a cached version of the utility JS file. Not a full solution for the related issue.

fix: Add query parameter to static resources

---

documentation/markdown/README.md
documentation/markdown/features.md
documentation/mkdocs.yml

An attempt to keep track of the features offered out of the box by the server.

docs: Describe server feature set

---

eslint.config.js
eslint/general.js
package-lock.json
package.json
src/util/StreamUtil.ts
test/unit/identity/configuration/IdentityProviderFactory.test.ts
test/unit/init/cluster/ClusterManager.test.ts
test/unit/storage/DataAccessorBasedStore.test.ts
test/unit/storage/LockingResourceStore.test.ts

New linting library that we use seems to have very frequent updates. Not going to always follow them but with this PR we at least no longer use a beta version.

chore: Update linting dependency

---

documentation/markdown/usage/dev-configuration.md
src/init/AppRunner.ts
test/unit/init/AppRunner.test.ts

https://github.com/CommunitySolidServer/CommunitySolidServer/discussions/1770
Add some defaults when creating a server to simplify the process for users when starting the server through code.

Add server creation defaults

---

templates/pod/base/README$.md.hbs

Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1814

fix: Fix pod base URL in README template

---

documentation/markdown/contributing/release.md

Some minor tweaks to the steps when doing a release.

docs: Update release instructions

---

src/authorization/AcpUtil.ts
src/http/auxiliary/LinkMetadataGenerator.ts
src/http/input/metadata/AuthorizationParser.ts
src/http/input/metadata/CookieParser.ts
src/http/ldp/PostOperationHandler.ts
src/http/output/metadata/WacAllowMetadataWriter.ts
src/http/representation/N3Patch.ts
src/http/representation/RepresentationMetadata.ts
src/server/notifications/BaseChannelType.ts
src/storage/DataAccessorBasedStore.ts
src/storage/accessors/FileDataAccessor.ts
src/storage/accessors/SparqlDataAccessor.ts
src/storage/conversion/ContainerToTemplateConverter.ts
src/storage/conversion/DynamicJsonToTemplateConverter.ts
src/storage/conversion/QuadToRdfConverter.ts
src/storage/patch/ImmutableMetadataPatcher.ts
src/storage/patch/N3Patcher.ts
src/util/QuadUtil.ts
src/util/TermUtil.ts
src/util/Vocabularies.ts
src/util/errors/HttpError.ts
test/unit/authorization/AcpReader.test.ts
test/unit/authorization/permissions/N3PatchModesExtractor.test.ts
test/unit/http/representation/RepresentationMetadata.test.ts
test/unit/storage/accessors/SparqlDataAccessor.test.ts
test/unit/storage/patch/RdfPatcher.test.ts
test/unit/storage/patch/SparqlUpdatePatcher.test.ts

Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1834
Title says it all

chore: Replace rdf-js import with @rdfjs/types

---

test/integration/IdentityTestState.ts

https://github.com/CommunitySolidServer/CommunitySolidServer/pull/1831
This is no longer necessary since dependencies have been updated

test: Remove workaround for authn library

---

README.md

add link to CSS-focused Matrix chatroom to README.md

---

src/pods/generate/BaseResourcesGenerator.ts
test/unit/pods/generate/BaseResourcesGenerator.test.ts

Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1887
Changing content-type through metadata changes is prevented on the server, so the only time this can occur is during resource initialization. This fixes the problem by combining data and metadata before the representation is written to the backend.

fix: Combine metadata with data when generating resources

---

package-lock.json

Closes https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1848

chore: Update @bergos/jsonparse to v1.4.2

---

src/storage/conversion/ConstantConverter.ts
test/unit/storage/conversion/ConstantConverter.test.ts

https://github.com/CommunitySolidServer/CommunitySolidServer/issues/1982
I did not find any branch I could use other than main sorry.

do not check MediaRanges on container

---

config/storage/middleware/base/base.json
config/storage/middleware/default.json

Something went wrong when merging main into next/major.

fix: Fix issue with configs after merge

---

src/storage/keyvalue/IndexedStorage.ts
src/storage/keyvalue/WrappedIndexedStorage.ts
test/unit/storage/keyvalue/WrappedIndexedStorage.test.ts

Allows IndexedStorage to have array fields.

feat: Allow IndexedStorage to have array fields

---

.github/workflows/npm-test.yml
package-lock.json
package.json

test: Include node v24 in the CI tests
